import { defineConfig } from 'vite';
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

// TASK 1: Consistent Versioning
// Try to read the version generated by scripts/update-build.cjs
let buildId = process.env.BUILD_ID || new Date().toISOString();
try {
  const versionPath = path.resolve(__dirname, 'public/version.json');
  if (fs.existsSync(versionPath)) {
    const versionData = JSON.parse(fs.readFileSync(versionPath, 'utf8'));
    buildId = versionData.version;
    console.log(`[Vite] Using buildId from version.json: ${buildId}`);
  }
} catch (e) {
  console.warn('[Vite] Could not read version.json, using fallback ID');
}

let gitSha = 'unknown';
try {
  gitSha = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
    .toString()
    .trim();
} catch {
  gitSha = process.env.GIT_SHA || gitSha;
}

export default defineConfig({
  plugins: [{
    name: 'nova-local-pilot-policy-esm',
    apply: 'serve',
    transform(code, id) {
      // The shared Electron policy is CommonJS. Rollup already handles it in
      // production; Vite's source server needs equivalent named ESM exports.
      if (!id.replace(/\\/g, '/').split('?')[0].endsWith('/electron/pilotNamePolicy.cjs')) return null;
      return { code: code.replace(/exports\.(\w+) = \1;/g, 'export { $1 };'), map: null };
    }
  }],
  define: {
    __BUILD_ID__: JSON.stringify(buildId),
    __GIT_SHA__: JSON.stringify(gitSha)
  },
  base: './',
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    chunkSizeWarningLimit: 700,
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (!id.includes('node_modules')) return undefined;
          if (id.includes('pixi.js') || id.includes('@pixi')) return 'vendor-pixi';
          if (id.includes('howler')) return 'vendor-audio';
          return 'vendor';
        }
      }
    }
  },
  server: {
    port: 3000
  }
});
