name = "burt-game"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
ENJIN_MOCK_MODE = "false"

[[d1_databases]]
binding = "WEB3_DB"
database_name = "nova-swarm-enjin-web3"
database_id = "8703b98a-6f68-443f-959b-e31873d2e15f"
