const UI={
 en:['Bonus Drones','SHOOT','Score target',"Shoot for exactly {score} bonus points. This reward is not multiplied. Do not collect this drone; contact is dangerous. Bonus cores are collected instead."],
 de:['Bonusdrohnen','SCHIESSEN','Punkteziel',"Abschießen bringt genau {score} Bonuspunkte. Diese Belohnung wird nicht multipliziert. Nicht einsammeln; Berührung ist gefährlich. Bonuskerne werden dagegen eingesammelt."],
 es:['Drones de bonificación','DISPARA','Objetivo de puntuación',"Derríbalo para obtener exactamente {score} puntos de bonificación. Esta recompensa no se multiplica. No recojas este dron; tocarlo es peligroso. Los núcleos de bonificación sí se recogen."],
 'pt-BR':['Drones de bônus','ATIRE','Alvo de pontuação',"Destrua para ganhar exatamente {score} pontos de bônus. Esta recompensa não é multiplicada. Não colete este drone; o contato é perigoso. Já os núcleos de bônus devem ser coletados."],
 ru:['Бонусные дроны','СТРЕЛЯЙ','Цель для набора очков',"Сбейте дрон и получите ровно {score} бонусных очков. Эта награда не умножается. Не пытайтесь подобрать дрон: столкновение опасно. Бонусные ядра, напротив, нужно подбирать."],
 'zh-CN':['奖励无人机','射击','得分目标',"击落后获得恰好{score}点奖励分数，不受倍率影响。不要尝试拾取无人机，碰撞有危险。奖励核心则需要拾取。"],
 ja:['ボーナスドローン','撃て','得点ターゲット',"撃墜すると必ず{score}点のボーナス。この報酬に倍率はかかりません。ドローンは回収できず、接触は危険です。ボーナスコアは回収してください。"],
 ko:['보너스 드론','사격','점수 표적',"격추하면 정확히 {score}점의 보너스를 얻습니다. 이 보상에는 배수가 적용되지 않습니다. 드론은 수집할 수 없으며 접촉하면 위험합니다. 보너스 코어는 수집해야 합니다."]
};
const STORIES={
 en:['A forked courier carrying stolen navigation royalties in its wing vaults.','Its armored jaws clamp a payroll capsule shut, even after the crew is long gone.','A three armed rotor that sorts salvage claims while its whole body spins.','A flying bullion safe with square cargo blocks and no interest in stopping.','Scissor wings fold around a contraband ledger stolen from the Cabinet.','A delivery shuttle whose dead transponder still insists its valuable parcel is empty.','Two treasury pods share one nervous little flight controller.','A crowned customs collector that kept the fees after its checkpoint fell.','A chain of armored cash boxes follows a single overworked guidance unit.','Its long antenna trades stolen market signals between abandoned stations.','Three forward prongs defend a shipment of counterfeit clearance stamps.','A mining drill that found the payroll vault before it found any ore.','A crab shaped salvage tug that refuses to release its prize.','A serrated recovery drone built to cut valuables out of dead warships.','The last mobile vault of a bank that vanished from every chart.'],
 de:['Ein gegabelter Kurier transportiert gestohlene Navigationsgebühren in seinen Flügeltresoren.','Seine gepanzerten Kiefer halten eine Lohnkapsel fest verschlossen, lange nach dem Ende der Besatzung.','Ein dreiarmiger Rotor sortiert Bergungsansprüche, während sich sein ganzer Rumpf dreht.','Ein fliegender Goldtresor mit eckigen Frachtblöcken, der nicht anhalten will.','Scherenflügel umschließen ein aus dem Cabinet gestohlenes Schmuggelregister.','Ein Liefergleiter, dessen toter Transponder seine wertvolle Fracht weiterhin als leer meldet.','Zwei Schatzkammergondeln teilen sich eine nervöse Flugsteuerung.','Ein gekrönter Zolleintreiber behielt die Gebühren, nachdem sein Kontrollpunkt fiel.','Eine Kette gepanzerter Geldkassetten folgt einer einzigen überlasteten Lenkeinheit.','Seine lange Antenne handelt mit gestohlenen Marktsignalen verlassener Stationen.','Drei Frontzinken schützen eine Ladung gefälschter Freigabestempel.','Ein Bohrer fand den Lohntresor, bevor er auf Erz stieß.','Ein krabbenförmiger Bergungsschlepper lässt seine Beute nicht los.','Eine gezackte Bergungsdrohne schneidet Wertsachen aus zerstörten Kriegsschiffen.','Der letzte mobile Tresor einer Bank, die von allen Karten verschwand.'],
 es:['Un mensajero bifurcado lleva tasas de navegación robadas en las cajas fuertes de sus alas.','Sus mandíbulas blindadas siguen cerrando una cápsula de nóminas mucho después de desaparecer la tripulación.','Un rotor de tres brazos clasifica derechos de salvamento mientras gira todo su cuerpo.','Una caja fuerte voladora con bloques de carga cuadrados que no piensa detenerse.','Sus alas de tijera protegen un registro de contrabando robado al Cabinet.','Una lanzadera cuyo transpondedor muerto insiste en que su valioso paquete está vacío.','Dos cápsulas del tesoro comparten un pequeño controlador de vuelo nervioso.','Un recaudador coronado que conservó las tasas cuando cayó su puesto aduanero.','Una cadena de cajas blindadas sigue a una sola unidad de guiado sobrecargada.','Su larga antena comercia con señales de mercado robadas entre estaciones abandonadas.','Tres puntas delanteras defienden un cargamento de sellos de autorización falsos.','Un taladro minero encontró la caja de nóminas antes que el mineral.','Un remolcador con forma de cangrejo se niega a soltar su botín.','Un dron dentado corta objetos valiosos de naves de guerra destruidas.','La última caja fuerte móvil de un banco borrado de todos los mapas.'],
 'pt-BR':['Um mensageiro bifurcado leva taxas de navegação roubadas nos cofres das asas.','Suas mandíbulas blindadas mantêm uma cápsula de pagamentos fechada mesmo após o fim da tripulação.','Um rotor de três braços organiza direitos de salvamento enquanto todo o corpo gira.','Um cofre voador de barras de ouro com blocos quadrados de carga que não quer parar.','As asas de tesoura envolvem um registro de contrabando roubado do Cabinet.','Uma nave de entregas cujo transponder morto insiste que sua encomenda valiosa está vazia.','Duas cápsulas do tesouro dividem um pequeno e nervoso controlador de voo.','Um cobrador coroado ficou com as taxas depois da queda de seu posto alfandegário.','Uma corrente de caixas blindadas segue uma única unidade de orientação sobrecarregada.','Sua longa antena negocia sinais de mercado roubados entre estações abandonadas.','Três pontas dianteiras defendem uma carga de carimbos de liberação falsos.','Uma broca de mineração encontrou o cofre de pagamentos antes de encontrar minério.','Um rebocador em forma de caranguejo se recusa a largar seu prêmio.','Um drone serrilhado corta objetos valiosos de naves de guerra destruídas.','O último cofre móvel de um banco que sumiu de todos os mapas.'],
 ru:['Раздвоенный курьер везёт украденные навигационные сборы в крыльевых сейфах.','Бронированные челюсти удерживают платёжную капсулу даже после исчезновения экипажа.','Трёхлучевой ротор сортирует права на трофеи, вращаясь всем корпусом.','Летающий сейф с золотом и квадратными грузовыми блоками не собирается останавливаться.','Крылья ножницами охватывают контрабандный реестр, украденный у Cabinet.','Доставочный челнок с мёртвым транспондером упорно объявляет ценный груз пустым.','Два казначейских отсека делят один нервный полётный контроллер.','Венценосный сборщик пошлин присвоил сборы после падения таможенного поста.','Цепочка бронированных денежных ящиков следует за перегруженным блоком наведения.','Длинная антенна торгует украденными рыночными сигналами заброшенных станций.','Три передних зубца защищают груз поддельных разрешительных штампов.','Шахтёрский бур нашёл платёжный сейф раньше руды.','Крабовидный спасательный буксир не желает отпускать добычу.','Зубчатый сборщик вырезает ценности из погибших военных кораблей.','Последний передвижной сейф банка, исчезнувшего со всех карт.'],
 'zh-CN':['分叉的信使将窃取的导航费用藏在翼部保险库里。','船员早已消失，装甲巨颚仍紧紧夹着薪资舱。','三臂转子一边旋转整个机身，一边整理打捞索赔。','装着方形货箱的飞行金库完全没有停下的打算。','剪刀状机翼包裹着从Cabinet偷来的走私账册。','运输艇的失效应答器仍坚持声称贵重包裹是空的。','两个金库舱共用一个紧张的小型飞行控制器。','加冕的关税收集机在检查站陷落后私吞了税款。','一串装甲钱箱跟随着唯一且不堪重负的制导单元。','长天线在废弃空间站之间贩卖窃取的市场信号。','前方三叉保护着一批伪造的通行印章。','采矿钻头还没找到矿石，就先找到了薪资保险库。','螃蟹状打捞拖船不肯放开自己的战利品。','锯齿回收机专门从废弃战舰中切出贵重物品。','一家从所有星图上消失的银行留下的最后一座移动金库。'],
 ja:['二股の運搬機。盗んだ航行料金を翼の金庫に隠している。','乗員が消えた後も、装甲の顎は給与カプセルを固く挟んでいる。','三本腕のローターが機体ごと回転しながら回収権を仕分けする。','四角い貨物ブロックを積んだ空飛ぶ金庫。止まる気はない。','はさみ状の翼がCabinetから盗んだ密輸台帳を包み込む。','故障した応答装置が、貴重な荷物は空だと言い張る配達艇。','二つの財宝ポッドが、神経質な小型飛行制御装置を共有している。','検問所が陥落した後も徴収金を手放さなかった王冠付きの税関機。','装甲現金箱の列が、働きすぎの誘導装置一つについていく。','長いアンテナで、放棄されたステーション間の盗んだ市場情報を取引する。','前方の三つの爪が、偽造通行印の積み荷を守る。','鉱石より先に給与金庫を掘り当てた採掘ドリル。','獲物を決して離さない、カニ型の回収曳航機。','沈黙した戦艦から貴重品を切り出す、鋸歯状の回収ドローン。','すべての星図から消えた銀行が残した、最後の移動金庫。'],
 ko:['갈라진 날개의 운송기가 훔친 항행 수수료를 날개 금고에 싣고 다닌다.','승무원이 사라진 뒤에도 장갑 턱은 급여 캡슐을 굳게 물고 있다.','세 팔의 회전기가 몸 전체를 돌리며 인양 권리를 분류한다.','네모난 화물 블록을 실은 비행 금괴 금고는 멈출 생각이 없다.','가위 날개가 Cabinet에서 훔친 밀수 장부를 감싼다.','고장 난 응답기가 귀중한 소포를 계속 빈 화물이라고 우기는 배달선.','두 보물 포드가 신경질적인 소형 비행 제어기 하나를 공유한다.','검문소가 함락된 뒤에도 수수료를 챙긴 왕관 모양의 세금 징수기.','장갑 현금 상자의 행렬이 과로하는 유도 장치 하나를 따른다.','긴 안테나로 버려진 정거장 사이에서 훔친 시장 정보를 거래한다.','앞쪽의 세 갈래 발톱이 위조 통행 도장 화물을 지킨다.','광석보다 먼저 급여 금고를 발견한 채굴 드릴.','전리품을 놓으려 하지 않는 게 모양의 인양 예인선.','파괴된 전함에서 귀중품을 잘라내는 톱니 회수 드론.','모든 성도에서 사라진 은행의 마지막 이동 금고.']
};
export function getBonusDroneSourceText(locale='en') {
 const row=UI[locale]||UI.en;
 return Object.fromEntries(UI.en.slice(0,3).map((key,i)=>[key,row[i]]));
}
export function getBonusDroneText(profile,locale='en') {
 const ui=UI[locale]||UI.en, stories=STORIES[locale]||STORIES.en;
 const legacy={en:'An older bounty frame still carrying sealed cargo through the swarm.',de:'Eine ältere Beutedrohne trägt weiterhin versiegelte Fracht durch den Schwarm.',es:'Un antiguo modelo de recompensa sigue transportando carga sellada entre el enjambre.','pt-BR':'Um antigo modelo de recompensa ainda transporta carga lacrada pelo enxame.',ru:'Старый трофейный дрон всё ещё везёт запечатанный груз сквозь рой.','zh-CN':'老式赏金无人机仍载着密封货物穿行于虫群之中。',ja:'古い賞金ドローンが、封印された貨物を今も群れの中で運び続けている。',ko:'구형 현상금 드론이 아직도 밀봉된 화물을 싣고 군집 사이를 누빈다.'};
 return {name:profile.name,description:profile.legacy?(legacy[locale]||legacy.en):stories[profile.index-4],tip:ui[3].replace('{score}',String(profile.score)),role:ui[2],rarity:ui[0]};
}
