import { getExpandedSnakeText } from './expandedSnakeText.js';
// English source and complete eight-language entries for the new encounter.
const UI = {
  en: ['Space Snakes', 'COLLECT: {name}', 'COLLECTED: {name}', 'SCORE ×2', 'Segmented predator', 'Bonus core'],
  de: ['Weltraumschlangen', 'EINSAMMELN: {name}', 'EINGESAMMELT: {name}', 'PUNKTE ×2', 'Segmentierter Jäger', 'Bonuskern'],
  es: ['Serpientes espaciales', 'RECOGE: {name}', 'RECOGIDO: {name}', 'PUNTOS ×2', 'Depredador segmentado', 'Núcleo de bonificación'],
  ru: ['Космические змеи', 'ПОДБЕРИ: {name}', 'ПОЛУЧЕНО: {name}', 'ОЧКИ ×2', 'Сегментированный хищник', 'Бонусное ядро'],
  'zh-CN': ['太空巨蛇', '拾取：{name}', '已拾取：{name}', '得分 ×2', '节段掠食者', '奖励核心'],
  'pt-BR': ['Serpentes espaciais', 'COLETE: {name}', 'COLETADO: {name}', 'PONTOS ×2', 'Predador segmentado', 'Núcleo de bônus'],
  ko: ['우주 뱀', '획득: {name}', '획득 완료: {name}', '점수 ×2', '분절형 포식자', '보너스 코어'],
  ja: ['宇宙蛇', '回収：{name}', '回収完了：{name}', 'スコア ×2', '分節型捕食者', 'ボーナスコア']
};
export function getCoreSerpentSourceText(locale) {
  const values = UI[locale] || UI.en;
  return { ...Object.fromEntries(UI.en.map((key, i) => [key, values[i]])), 'SPACE SNAKES': values[0].toUpperCase() };
}

const STORIES = {
 en: [
  ['Cinder Maw', 'The first Cinder Maw was mistaken for a broken fuel pipeline drifting through the ashes of Berget-9. A salvage crew cut its anchor cable. Every valve opened like an eye, and the pipeline swallowed the tug. The Swarm had threaded a hunting intelligence through stolen reactor chambers. Each armored vertebra now remembers the heat of a different wreck. It follows broad, burning curves, offering its head as bait while the rest of its body closes the route behind you.', 'Shoot through the connected body and leave room for its return sweep. Destroyed sections shorten the creature; the surviving front continues hunting.'],
  ['Thorn Cathedral', 'The abandoned garden ships of the Nine-Moon Choir carried seed vaults armored against a century of radiation. The Swarm taught those vaults to grow teeth. Thorn Cathedral is a traveling nursery of metal: each rib shelters another predatory node, and its spines comb the wreckage for fresh material. Its slow double turns resemble a prayer written by something that has never understood mercy. Pilots who mistook the first turn for retreat left their names inside its next layer of armor.', 'Its long body folds across its own route. Attack the outside of the bend and avoid being enclosed between returning sections.'],
  ['Violet Widow', 'Clerk Null found the Widow in a navigational archive that kept recording voyages after every ship had disappeared. The signal was a lure. The creature had learned the shape of rescue approaches and woven them into a beautiful, fatal dance. Its violet organs flash through black armor as it crosses and recrosses the same patch of space, gathering impatient pilots into the loop. Nobody knows what lies at the center of its memory. The Cabinet has stopped sending rescue ships to ask.', 'Wait outside the crossing before changing lanes. Its body is vulnerable throughout the dance; patient sustained fire is safer than chasing the head.'],
  ['Abyss Crown', 'Before the Cabinet named the sectors, deep-space relay cables carried voices across the dark. Something answered from inside the insulation. Abyss Crown grew around that answer: a cold, plated spine with a crown of stolen antennae and a luminous nervous system that refuses to die with its head. Its enormous curves still trace old communication routes. For a moment, damaged receivers can hear the missing crews speaking in perfect unison. Then the creature turns toward the transmission.', 'This is a long-bodied species. Cut down its sections while preserving an escape lane; destroying the head alone does not stop the remaining body.']
 ],
 de: [
  ['Glutrachen', 'Der erste Glutrachen wurde für eine zerbrochene Treibstoffleitung in der Asche von Berget-9 gehalten. Ein Bergungsteam kappte das Ankerkabel. Jedes Ventil öffnete sich wie ein Auge, und die Leitung verschlang den Schlepper. Der Schwarm hatte einen Jagdverstand durch gestohlene Reaktorkammern gefädelt. Jeder gepanzerte Wirbel bewahrt die Hitze eines anderen Wracks. Das Wesen zieht weite Bögen, bietet seinen Kopf als Köder an und schließt mit dem Körper den Rückweg.', 'Feuere durch den verbundenen Körper und halte Platz für den Rückschwenk frei. Zerstörte Segmente verkürzen das Wesen; die überlebende Spitze jagt weiter.'],
  ['Dornenkathedrale', 'Die verlassenen Gartenschiffe des Neunmondchors trugen gegen Strahlung gepanzerte Saatgutkammern. Der Schwarm brachte ihnen bei, Zähne zu bilden. Die Dornenkathedrale ist eine wandernde Brutstätte aus Metall: Jede Rippe schützt einen weiteren Jagdknoten, ihre Dornen kämmen Wracks nach Material ab. Ihre langsamen Doppelwendungen gleichen einem Gebet ohne Gnade. Piloten, die die erste Wende für einen Rückzug hielten, hinterließen ihre Namen in der nächsten Panzerschicht.', 'Der lange Körper faltet sich über seine eigene Bahn. Greife außen an der Kurve an und lass dich nicht zwischen zurückkehrenden Segmenten einschließen.'],
  ['Violette Witwe', 'Clerk Null fand die Witwe in einem Navigationsarchiv, das noch Reisen aufzeichnete, als alle Schiffe verschwunden waren. Das Signal war ein Köder. Das Wesen hatte Rettungsanflüge zu einem schönen, tödlichen Tanz verwoben. Violette Organe blitzen durch schwarze Panzerung, während es denselben Raum wiederholt kreuzt und ungeduldige Piloten in seine Schleife lockt. Niemand kennt den Kern seiner Erinnerung. Cabinet schickt keine Rettungsschiffe mehr, um nachzufragen.', 'Warte außerhalb der Kreuzung, bevor du die Bahn wechselst. Der Körper bleibt während des Tanzes verwundbar; stetiges Feuer ist sicherer als die Jagd nach dem Kopf.'],
  ['Abgrundkrone', 'Lange vor den Sektornamen trugen Relaiskabel Stimmen durch die Dunkelheit. Etwas antwortete aus ihrer Isolierung. Darum wuchs die Abgrundkrone: ein kaltes, gepanzertes Rückgrat mit gestohlenen Antennen und einem leuchtenden Nervensystem, das den Verlust des Kopfes überlebt. Ihre weiten Bögen folgen alten Funkrouten. Beschädigte Empfänger hören kurz die vermissten Besatzungen im Gleichklang. Dann wendet sich das Wesen der Übertragung zu.', 'Ein langer, gepanzerter Körper. Zerstöre ihre Segmente und halte einen Fluchtweg frei; der Verlust des Kopfes stoppt den restlichen Körper nicht.']
 ],
 es: [
  ['Fauces de Ceniza', 'Las primeras Fauces de Ceniza parecían una tubería rota entre las cenizas de Berget-9. Un equipo de rescate cortó su cable. Las válvulas se abrieron como ojos y la tubería devoró el remolcador. El Enjambre había enlazado cámaras de reactor robadas con una inteligencia cazadora. Cada vértebra blindada recuerda el calor de otro naufragio. Traza amplias curvas y ofrece la cabeza como cebo mientras el cuerpo cierra la salida.', 'Dispara a través del cuerpo conectado y deja espacio para el barrido de regreso. Los segmentos destruidos la acortan; el frente superviviente sigue cazando.'],
  ['Catedral de Espinas', 'Las naves jardín abandonadas del Coro de las Nueve Lunas llevaban semillas protegidas de la radiación. El Enjambre les enseñó a criar dientes. Catedral de Espinas es un vivero de metal: cada costilla protege otro nodo depredador y sus espinas recogen material de los restos. Sus lentos giros dobles parecen una plegaria sin piedad. Los pilotos que confundieron el primer giro con una retirada dejaron sus nombres en la siguiente capa de blindaje.', 'El cuerpo largo se pliega sobre su propia ruta. Ataca desde fuera de la curva y evita quedar encerrado entre los segmentos que regresan.'],
  ['Viuda Violeta', 'Clerk Null encontró a la Viuda en un archivo que seguía registrando viajes después de desaparecer todas las naves. La señal era un señuelo. La criatura había aprendido las rutas de rescate y las había tejido en una danza hermosa y mortal. Sus órganos violetas brillan bajo el blindaje negro mientras cruza una y otra vez el mismo espacio, atrapando a pilotos impacientes. Nadie conoce el centro de su memoria. Cabinet ya no envía rescates para averiguarlo.', 'Espera fuera del cruce antes de cambiar de carril. El cuerpo sigue vulnerable durante la danza; disparar con paciencia es más seguro que perseguir la cabeza.'],
  ['Corona Abisal', 'Antes de que Cabinet nombrara los sectores, los cables de comunicación llevaban voces por la oscuridad. Algo respondió desde su aislamiento. Corona Abisal creció alrededor de esa respuesta: una columna blindada con antenas robadas y nervios luminosos que sobreviven a la pérdida de la cabeza. Sus curvas siguen rutas de comunicación antiguas. Los receptores dañados oyen a las tripulaciones perdidas al unísono. Entonces la criatura gira hacia la transmisión.', 'Es una especie de cuerpo largo. Destruye sus segmentos conservando una salida; destruir solo la cabeza no detiene al resto del cuerpo.']
 ],
 'pt-BR': [
  ['Mandíbula de Cinzas', 'A primeira Mandíbula de Cinzas parecia um duto rompido nas cinzas de Berget-9. Uma equipe de resgate cortou seu cabo. As válvulas se abriram como olhos, e o duto engoliu o rebocador. O Enxame havia ligado câmaras de reator roubadas a uma inteligência caçadora. Cada vértebra blindada guarda o calor de outro destroço. Ela traça curvas amplas e oferece a cabeça como isca enquanto o corpo fecha a saída.', 'Atire através do corpo conectado e deixe espaço para a varredura de retorno. Segmentos destruídos encurtam a criatura; a frente sobrevivente continua caçando.'],
  ['Catedral de Espinhos', 'As naves jardim abandonadas do Coro das Nove Luas carregavam sementes protegidas da radiação. O Enxame ensinou seus cofres a criar dentes. Catedral de Espinhos é um viveiro de metal: cada costela protege outro núcleo predador, e seus espinhos recolhem materiais dos destroços. Suas lentas curvas duplas parecem uma oração sem misericórdia. Pilotos que confundiram a primeira curva com uma retirada deixaram seus nomes na camada seguinte de armadura.', 'O corpo comprido se dobra sobre a própria rota. Ataque por fora da curva e evite ficar preso entre os segmentos que retornam.'],
  ['Viúva Violeta', 'Clerk Null encontrou a Viúva em um arquivo que ainda registrava viagens depois que todas as naves haviam sumido. O sinal era uma armadilha. A criatura havia aprendido rotas de resgate e tecido uma dança bela e mortal. Órgãos violetas brilham sob a armadura negra enquanto ela cruza o mesmo espaço repetidamente, prendendo pilotos impacientes. Ninguém conhece o centro de sua memória. Cabinet parou de enviar equipes para descobrir.', 'Espere fora do cruzamento antes de mudar de faixa. O corpo permanece vulnerável durante a dança; fogo constante é mais seguro do que perseguir a cabeça.'],
  ['Coroa Abissal', 'Antes dos nomes dos setores, cabos retransmissores levavam vozes pela escuridão. Algo respondeu de dentro do isolamento. A Coroa Abissal cresceu ao redor dessa resposta: uma coluna blindada com antenas roubadas e nervos luminosos que sobrevivem à perda da cabeça. Suas curvas seguem antigas rotas de comunicação. Receptores danificados ouvem as tripulações desaparecidas em uníssono. Então a criatura se volta para a transmissão.', 'É uma espécie de corpo longo. Destrua seus segmentos mantendo uma rota de fuga; destruir apenas a cabeça não detém o restante do corpo.']
 ],
 ru: [
  ['Пепельная пасть', 'Первую Пепельную пасть приняли за разорванный топливопровод среди пепла Бергет-9. Спасатели перерезали его трос. Клапаны раскрылись словно глаза, и труба проглотила буксир. Рой протянул охотничий разум через украденные реакторные камеры. Каждый бронированный позвонок хранит жар нового обломка. Существо движется широкими дугами, подставляет голову как приманку и перекрывает отступление телом.', 'Стреляй сквозь связанное тело и оставляй место для обратного прохода. Уничтоженные секции укорачивают существо; уцелевшая передняя часть продолжает охоту.'],
  ['Терновый собор', 'Заброшенные корабли-сады Хора Девяти Лун несли защищённые от радиации семенные хранилища. Рой научил их отращивать зубы. Терновый собор стал металлическим питомником: каждое ребро укрывает хищный узел, а шипы собирают материал среди обломков. Его медленные двойные повороты напоминают молитву без милосердия. Имена пилотов, принявших первый поворот за отступление, остались в следующем слое брони.', 'Длинное тело складывается поверх собственной траектории. Атакуй снаружи изгиба и не попадай между возвращающимися секциями.'],
  ['Фиолетовая вдова', 'Clerk Null нашёл Вдову в архиве, который записывал рейсы даже после исчезновения всех кораблей. Сигнал оказался приманкой. Существо изучило спасательные маршруты и сплело из них прекрасный смертельный танец. Фиолетовые органы мерцают под чёрной бронёй, пока оно снова пересекает тот же участок пространства, заманивая нетерпеливых пилотов. Никто не знает, что скрыто в его памяти. Cabinet больше не отправляет спасателей за ответом.', 'Подожди за пределами пересечения перед сменой полосы. Тело уязвимо во время танца; непрерывный огонь безопаснее погони за головой.'],
  ['Корона бездны', 'До появления названий секторов кабели ретрансляторов переносили голоса через тьму. Что-то ответило изнутри изоляции. Вокруг ответа выросла Корона бездны: бронированный позвоночник с украденными антеннами и светящейся нервной системой, переживающей потерю головы. Её дуги повторяют старые маршруты связи. Повреждённые приёмники слышат пропавшие экипажи, говорящие хором. Затем существо поворачивается к передатчику.', 'Длинное бронированное тело. Уничтожай секции, сохраняя путь отхода; потеря головы не останавливает оставшееся тело.']
 ],
 'zh-CN': [
  ['烬火巨颚', '第一条烬火巨颚曾被误认为是贝尔盖特九号灰烬中漂浮的断裂燃料管。打捞队切断缆绳后，所有阀门像眼睛般睁开，管道吞掉了拖船。虫群把狩猎智能穿过偷来的反应堆舱室，每一节装甲椎骨都记得一艘残骸的热量。它沿宽阔弧线游动，用头部引诱猎物，再用身体封住退路。', '向相连的身体持续射击，并为它的折返留出空间。摧毁节段会缩短巨蛇，但幸存的前端会继续狩猎。'],
  ['荆棘圣堂', '九月合唱团废弃的花园船曾携带防辐射种子库。虫群教会这些舱室长出利齿。荆棘圣堂是一座移动的金属育场，每根肋骨都庇护着捕食节点，尖刺从残骸中搜集材料。它缓慢的双重转弯像一段毫无慈悲的祷文。把第一次转向误当成撤退的飞行员，名字都留在了下一层装甲里。', '长长的身体会折回自己的航迹。从弯道外侧攻击，避免被折返的节段夹住。'],
  ['紫罗兰寡妇', 'Clerk Null 在一个所有舰船失踪后仍持续记录航程的档案中发现了寡妇。信号其实是诱饵。它学会救援航线，将其编织成优美而致命的舞蹈。紫色器官从黑色装甲间闪烁，它反复穿越同一片空间，把急躁的飞行员卷入回环。没人知道它的记忆深处藏着什么。Cabinet 已不再派救援船去寻找答案。', '换道前先在交叉点外等待。舞动中的身体始终可以受伤；耐心持续射击比追逐头部更安全。'],
  ['深渊王冠', '在星区拥有名字之前，中继缆线就把声音送过黑暗。某种东西从绝缘层内部作出了回应。深渊王冠围绕着这个回应生长，形成覆甲脊柱、偷来的天线王冠，以及失去头部仍能运作的发光神经。它庞大的曲线依旧描摹古老通信路线。受损接收器会短暂听到失踪船员齐声说话，然后巨蛇便转向信号来源。', '它拥有修长的装甲身躯。逐节摧毁身体并保留逃生路线；仅摧毁头部无法阻止剩余身体。']
 ],
 ko: [
  ['잿불 아귀', '최초의 잿불 아귀는 베르게트 9의 잿더미에 떠다니는 끊어진 연료관으로 오인되었다. 인양대가 케이블을 자르자 모든 밸브가 눈처럼 열렸고 연료관은 예인선을 삼켰다. 군집은 훔친 원자로실에 사냥 지능을 꿰어 넣었다. 장갑 척추마다 다른 잔해의 열기가 남아 있다. 넓은 곡선으로 움직이며 머리를 미끼로 내밀고 몸으로 퇴로를 닫는다.', '연결된 몸에 사격하고 되돌아오는 경로에 여유를 남겨라. 마디를 파괴하면 몸이 짧아지지만 살아남은 앞부분은 계속 사냥한다.'],
  ['가시 성당', '아홉 달 합창단의 버려진 정원선에는 방사선을 견디는 종자 보관실이 있었다. 군집은 그 보관실에 이빨을 기르는 법을 가르쳤다. 가시 성당은 움직이는 금속 양육장이다. 갈비뼈마다 포식 노드를 품고 가시로 잔해에서 재료를 모은다. 느린 이중 회전은 자비 없는 기도 같다. 첫 회전을 후퇴로 착각한 조종사의 이름은 다음 장갑층에 남았다.', '긴 몸이 자신의 경로 위로 접힌다. 굽이 바깥에서 공격하고 돌아오는 마디 사이에 갇히지 마라.'],
  ['보랏빛 과부', 'Clerk Null은 모든 함선이 사라진 뒤에도 항해를 기록하는 자료실에서 과부를 발견했다. 신호는 미끼였다. 생물은 구조 접근 경로를 배워 아름답고 치명적인 춤으로 엮었다. 검은 장갑 사이로 보랏빛 장기가 번쩍이며 같은 공간을 거듭 가로질러 성급한 조종사를 고리에 가둔다. 기억의 중심에 무엇이 있는지는 아무도 모른다. Cabinet은 더는 답을 찾으러 구조선을 보내지 않는다.', '교차 지점 바깥에서 기다렸다가 경로를 바꿔라. 춤추는 동안에도 몸은 취약하다. 머리를 쫓기보다 꾸준히 사격하는 편이 안전하다.'],
  ['심연의 왕관', '구역에 이름이 붙기 전부터 중계 케이블은 어둠 너머로 목소리를 전했다. 절연체 안에서 무언가가 답했다. 그 응답을 둘러싸고 심연의 왕관이 자랐다. 훔친 안테나를 쓴 장갑 척추와 머리를 잃어도 살아 있는 빛나는 신경계다. 거대한 곡선은 옛 통신 경로를 따른다. 손상된 수신기에서 실종된 승무원의 목소리가 합창처럼 들린다. 그러면 생물이 송신원으로 몸을 돌린다.', '길고 단단한 몸을 지녔다. 탈출로를 남기며 마디를 파괴하라. 머리만 파괴해도 남은 몸은 멈추지 않는다.']
 ],
 ja: [
  ['灰燼の大顎', '最初の灰燼の大顎は、ベルゲット9の灰の中を漂う壊れた燃料管だと思われていた。回収班が係留索を切ると、弁が一斉に目のように開き、管が曳航船を飲み込んだ。スウォームは盗んだ炉心区画に狩猟知能を通していた。装甲の椎骨はそれぞれ別の残骸の熱を覚えている。大きな弧を描き、頭を囮に差し出しながら胴で退路を塞ぐ。', '連なった胴体を撃ち、折り返しの余地を残そう。節を壊すと短くなるが、生き残った先頭は狩りを続ける。'],
  ['棘の大聖堂', '九月合唱団の放棄された庭園船には、放射線を防ぐ種子庫があった。スウォームはそこに牙を生やした。棘の大聖堂は移動する金属の苗床だ。肋骨ごとに捕食ノードを守り、棘で残骸から素材を集める。ゆっくりした二重の旋回は、慈悲を知らない祈りに似ている。最初の旋回を撤退だと思った操縦士の名は、次の装甲層に残された。', '長い胴体が自分の軌道に折り重なる。曲がり角の外側から攻撃し、戻ってくる節の間に閉じ込められないようにしよう。'],
  ['紫の未亡人', 'Clerk Nullは全艦が消えた後も航海を記録し続ける資料庫で未亡人を見つけた。信号は罠だった。生物は救助の進入路を学び、美しく致命的な舞に編み直していた。黒い装甲の隙間から紫の器官が輝き、同じ宙域を繰り返し横切って焦る操縦士を輪の中に誘う。記憶の中心に何があるのか、誰も知らない。Cabinetはもう答えを求めて救助船を送らない。', '交差点の外で待ってから進路を変えよう。舞っている間も胴体は攻撃できる。頭を追うより持続射撃のほうが安全だ。'],
  ['深淵の王冠', 'セクターに名が付く前、中継ケーブルは暗闇の向こうへ声を運んでいた。絶縁材の内側から何かが答えた。その返答を核に深淵の王冠は育った。盗んだアンテナを冠にした装甲の背骨と、頭を失っても生きる発光神経系。その巨大な曲線は今も古い通信路をなぞる。壊れた受信機から行方不明の乗員が声をそろえて話す。すると生物は送信元へ向き直る。', '長い胴体を持つ種。逃げ道を確保しながら節を破壊しよう。頭だけを壊しても残った胴体は止まらない。']
 ]
};
export function getSpaceSnakeText(index, locale = 'en') {
 if(index>=4)return {...getExpandedSnakeText(index,locale),signalClass:(UI[locale]||UI.en)[4]};
 const [name, description, tip] = (STORIES[locale] || STORIES.en)[index];
 return { name, description, tip, signalClass: (UI[locale] || UI.en)[4] };
}
