// Proper callsigns remain recognizable; the instruction and response localize.
const TEXT={
  en:{payback:'{wing} · You got us out. Our turn.',paybackHelp:'Rescue both fighters. After their escort ends, the same wing can return once against one rival weapon in this run.',molt:'SERPENT MOLT',moltControl:'MOVING ARMOUR COVER',moltHelp:'Cinder snakes can shed armour while alive. Plates block shots from both sides, including Pierce and drones. Use them as cover or shoot them to reopen a lane. They cannot hurt your ship and soon drift away.'},
  de:{payback:'{wing} · Du hast uns befreit. Jetzt sind wir dran.',paybackHelp:'Befreie beide Jäger. Nach ihrem Begleiteinsatz kann dieselbe Staffel in diesem Lauf einmal gegen eine Rivalenwaffe zurückkehren.',molt:'SCHLANGENHÄUTUNG',moltControl:'BEWEGLICHE PANZERDECKUNG',moltHelp:'Cinder-Schlangen können ihren Panzer lebend abwerfen. Platten blockieren Schüsse von beiden Seiten, auch Pierce und Drohnen. Nutze sie als Deckung oder zerschieße sie für eine freie Schussbahn. Sie verletzen dein Schiff nicht und treiben bald davon.'},
  es:{payback:'{wing} · Nos sacaste de ahí. Ahora nos toca.',paybackHelp:'Rescata a ambos cazas. Tras terminar su escolta, la misma ala puede regresar una vez en esta partida para atacar un arma rival.',molt:'MUDA DE SERPIENTE',moltControl:'COBERTURA MÓVIL DE ARMADURA',moltHelp:'Las serpientes Cinder pueden desprenderse de su armadura en vida. Las placas bloquean disparos de ambos bandos, incluidos Pierce y drones. Úsalas como cobertura o destrúyelas para abrir una línea de tiro. No dañan tu nave y pronto se alejan.'},
  ru:{payback:'{wing} · Ты нас вытащил. Теперь наш черёд.',paybackHelp:'Спасите оба истребителя. После завершения сопровождения то же звено может один раз за этот вылет вернуться и атаковать одно орудие соперника.',molt:'ЛИНЬКА ЗМЕЯ',moltControl:'ПОДВИЖНОЕ УКРЫТИЕ ИЗ БРОНИ',moltHelp:'Змеи Cinder могут сбрасывать броню, оставаясь живыми. Пластины блокируют выстрелы обеих сторон, включая Pierce и дроны. Используйте их как укрытие или разбейте, чтобы освободить линию огня. Они не вредят вашему кораблю и вскоре уплывают.'},
  'zh-CN':{payback:'{wing} · 你救了我们。这次轮到我们。',paybackHelp:'救出两架战机。护航结束后，同一编队可在本局中返回一次，攻击劲敌的一侧武器。',molt:'巨蛇蜕甲',moltControl:'移动装甲掩体',moltHelp:'Cinder巨蛇可在存活时蜕去装甲。甲片会阻挡双方射击，包括Pierce和无人机。利用它们掩护自己，或击碎它们以打开射击通道。甲片不会伤害你的飞船，并会很快飘走。'},
  'pt-BR':{payback:'{wing} · Você nos salvou. Agora é nossa vez.',paybackHelp:'Resgate os dois caças. Após a escolta, a mesma ala pode voltar uma vez nesta partida para atacar uma arma rival.',molt:'MUDA DA SERPENTE',moltControl:'COBERTURA MÓVEL DE ARMADURA',moltHelp:'Serpentes Cinder podem soltar a armadura enquanto vivem. As placas bloqueiam tiros dos dois lados, incluindo Pierce e drones. Use-as como cobertura ou destrua-as para abrir uma linha de tiro. Elas não ferem sua nave e logo se afastam.'},
  ko:{payback:'{wing} · 우리를 구해 줬지. 이번엔 우리 차례야.',paybackHelp:'전투기 두 대를 모두 구출하세요. 호위가 끝난 뒤 같은 편대가 이번 플레이에서 한 번 돌아와 라이벌 무기 하나를 공격할 수 있습니다.',molt:'뱀의 탈피',moltControl:'움직이는 장갑 엄폐물',moltHelp:'Cinder 뱀은 살아 있는 동안 장갑을 벗을 수 있습니다. 장갑판은 Pierce와 드론을 포함한 양쪽의 탄을 막습니다. 엄폐물로 쓰거나 쏴서 사격로를 여세요. 장갑판은 플레이어의 함선을 해치지 않으며 곧 떠내려갑니다.'},
  ja:{payback:'{wing} · 助けてくれたね。今度はこっちの番だ。',paybackHelp:'戦闘機を2機とも救出しよう。護衛が終わると、同じ編隊がこのラン中に一度戻り、ライバルの武装1つを攻撃できる。',molt:'サーペントの脱皮',moltControl:'動く装甲の遮蔽物',moltHelp:'Cinderの蛇は生きたまま装甲を脱ぐことがある。装甲板はPierceやドローンを含む両側の弾を止める。遮蔽物として使うか、撃ち壊して射線を開こう。自機にはダメージを与えず、ほどなく流れ去る。'}
};
export const ENCOUNTER_EVOLUTION_ENGLISH=Object.freeze(TEXT.en);
export function getEncounterEvolutionSourceText(locale){
  return Object.fromEntries(Object.keys(TEXT.en).map(key=>[TEXT.en[key],(TEXT[locale]||TEXT.en)[key]]));
}
