// Stylized species names intentionally remain consistent across languages.
const names=['Grave Eel','Crimson Hammer','Mantis Coil','Sunforge Wyrm','Obsidian Sawtooth','Pearl Lamprey','Copper Tempest','Amethyst Oracle','Carrion Procession','Eclipse Dragon'];
const entries={
 en:[
 ['Grave Eel was born in the ossuary barges of a vanished colony. The Swarm threaded their memorial plates onto a living cable and taught it to follow distress beacons. Its pale skull remembers no pilot, but its long ribbon of vertebrae still carries their names.','The thin body changes from ribbon sweeps to tight crossings. Fire along its length and keep a lateral escape route.'],
 ['Crimson Hammer once opened asteroid vaults for mining fleets. When the crews stopped answering, the excavation head began choosing its own targets. It now breaks hulls with its broad red jaws, turning sharply after each apparently clumsy pass.','Expect wide hooks followed by abrupt slaloms. Let the heavy head pass before crossing the shorter body.'],
 ['Mantis Coil escaped a nursery that grew surgical machines. Its paired scythes were designed to save damaged ships; the Swarm reversed that instruction. The creature now measures every moving light as an incision, sewing elegant crossings through the battlefield.','Watch the hooked head during slaloms. Sustained fire through returning sections is safer than pursuing its fast turns.'],
 ['Sunforge Wyrm carries the stolen heart of a stellar foundry. Its golden crown once focused sunlight onto unfinished hulls. Now each orbit feeds a furnace mouth, and the old workers recognize its breathing in the heat that washes across their receivers.','Its broad orbit gradually becomes a closing coil. Attack outside the curve and move before the body closes your lane.'],
 ['Obsidian Sawtooth was assembled from the cutters that dismantled the first Cabinet prison. It swallowed the doors before the prisoners could leave. Black overlapping blades now grind along its spine, changing direction as if searching for the sound of another lock.','The angular sweep blends into different routes. Read the head movement and avoid chasing between its saw-edged sections.'],
 ['Pearl Lamprey lived beneath the ice of an abandoned refueling moon. Salvagers followed its blue lure into a reservoir that had become a mouth. Its pearlescent armor hides a stolen cooling system; the circular jaws drink engine light while the long body winds behind.','Keep clear of the tight coil and fire through its many sections. The bright lure is part of the head, not a pickup.'],
 ['Copper Tempest nested inside a storm-harvesting array. The first repair crew heard thunder through disconnected radios. Its branching horns now gather charge from the wreckage, and its restless body stitches broken lightning routes across open space.','Fast slaloms turn into broad sweeps. Watch the charge ring before its aimed volley and keep moving across the firing line.'],
 ['Amethyst Oracle was found in a prediction engine that foretold the loss of its own crew. Three crystalline eyes remained lit after shutdown. The Swarm gave those eyes a spine, and the creature began tracing futures that always ended with a ship inside its jaws.','Do not wait at the center of its figure-eight. Its next route blends in smoothly; use that transition to change lanes.'],
 ['Carrion Procession follows the oldest salvage lanes with fourteen rusted chambers clicking behind its skull. Each chamber was once a recovery drone. Their rescue signals still work, but the procession answers them only when something nearby is dying.','The longest body can seal several lanes. Work on exposed sections from the outside and preserve a clear retreat.'],
 ['Eclipse Dragon emerged when a solar shield failed to reopen after an artificial night. Its white crown reflects starlight while the throat absorbs it. The missing shield operators survive only as a rhythm in its vast breathing, heard just before the creature turns.','Its large head leads hooks, orbits and crossings. Respect the changing route; breaking the head does not kill the remaining spine.']
 ],
 de:[
 ['Grave Eel entstand in den Totenbarken einer verschwundenen Kolonie. Der Schwarm fädelte ihre Gedenkplatten auf ein lebendes Kabel und lehrte es, Notsignalen zu folgen. Der bleiche Schädel erinnert sich an keinen Piloten, doch die lange Wirbelkette trägt noch ihre Namen.','Der schmale Körper wechselt von weiten Bögen zu engen Kreuzungen. Schieße längs der Kette und halte einen seitlichen Fluchtweg frei.'],
 ['Crimson Hammer öffnete einst Asteroidentresore für Bergbauflotten. Als die Besatzungen verstummten, suchte sich der Bohrkopf eigene Ziele. Heute zerbricht er Rümpfe mit breiten roten Kiefern und wendet nach jedem scheinbar plumpen Vorbeiflug scharf.','Auf weite Haken folgen schnelle Slaloms. Lass den schweren Kopf passieren, bevor du den kürzeren Körper kreuzt.'],
 ['Mantis Coil entkam einer Brutstätte für chirurgische Maschinen. Seine Sicheln sollten beschädigte Schiffe retten; der Schwarm kehrte den Befehl um. Nun betrachtet das Wesen jedes bewegte Licht als Schnittstelle und näht elegante Kreuzungen durch das Schlachtfeld.','Beobachte den Sichelschädel im Slalom. Dauerfeuer auf zurückkehrende Segmente ist sicherer als die Verfolgung schneller Wendungen.'],
 ['Sunforge Wyrm trägt das gestohlene Herz einer Sternenschmiede. Seine goldene Krone bündelte einst Sonnenlicht auf unfertige Rümpfe. Nun speist jede Umkreisung den Ofenrachen; ehemalige Arbeiter erkennen sein Atmen an der Hitze in ihren Empfängern.','Die weite Umlaufbahn wird zur engen Schleife. Greife außen an und wechsle die Bahn, bevor der Körper sie schließt.'],
 ['Obsidian Sawtooth besteht aus den Schneidern des ersten Cabinet-Gefängnisses. Es verschlang die Türen, bevor die Gefangenen fliehen konnten. Schwarze Klingen mahlen entlang seiner Wirbelsäule und wechseln die Richtung, als suchten sie das Geräusch eines weiteren Schlosses.','Die kantigen Bögen gehen in neue Routen über. Folge dem Kopf mit den Augen und jage nicht zwischen die gezackten Segmente.'],
 ['Pearl Lamprey lebte unter dem Eis eines verlassenen Tankmondes. Bergungsleute folgten seinem blauen Locklicht in ein Reservoir, das zum Maul geworden war. Perlmuttrüstung verbirgt ein gestohlenes Kühlsystem; runde Kiefer trinken Triebwerkslicht, während der lange Körper folgt.','Meide die enge Schleife und beschieße die vielen Segmente. Das helle Locklicht gehört zum Kopf und ist kein Sammelobjekt.'],
 ['Copper Tempest nistete in einer Anlage zur Sturmenergiegewinnung. Reparaturteams hörten Donner aus abgetrennten Funkgeräten. Verzweigte Hörner sammeln heute Ladung aus Wracks, und der ruhelose Körper zeichnet zerbrochene Blitzbahnen in den Weltraum.','Schnelle Slaloms werden zu weiten Bögen. Achte auf den Ladering vor der gezielten Salve und verlasse die Schusslinie.'],
 ['Amethyst Oracle lag in einer Vorhersagemaschine, die den Verlust ihrer Besatzung angekündigt hatte. Drei Kristallaugen leuchteten nach der Abschaltung weiter. Der Schwarm gab ihnen eine Wirbelsäule; ihre Zukunftsbilder enden seither immer mit einem Schiff im Rachen.','Warte nicht in der Mitte der Acht. Die nächste Route setzt sanft ein; nutze den Übergang zum Bahnwechsel.'],
 ['Carrion Procession folgt alten Bergungsrouten mit vierzehn rostigen Kammern hinter dem Schädel. Jede war einst eine Rettungsdrohne. Ihre Notsignale funktionieren noch, doch die Prozession antwortet nur, wenn in ihrer Nähe etwas stirbt.','Der längste Körper kann mehrere Bahnen sperren. Zerstöre freie Segmente von außen und halte den Rückzug offen.'],
 ['Eclipse Dragon erschien, als ein Sonnenschild nach künstlicher Nacht geschlossen blieb. Die weiße Krone reflektiert Sternenlicht, der Rachen verschluckt es. Die verschwundenen Bediener leben nur als Rhythmus seines gewaltigen Atems weiter, hörbar kurz vor der Wendung.','Der große Kopf führt Haken, Kreise und Kreuzungen an. Achte auf neue Routen; der Tod des Kopfes beendet die Jagd nicht.']
 ],
 es:[
 ['Grave Eel nació en las barcazas funerarias de una colonia desaparecida. El Enjambre ensartó sus placas conmemorativas en un cable vivo y le enseñó a seguir señales de socorro. El cráneo pálido no recuerda a ningún piloto, pero su larga columna conserva sus nombres.','El cuerpo fino pasa de barridos amplios a cruces cerrados. Dispara a lo largo de sus segmentos y conserva una salida lateral.'],
 ['Crimson Hammer abría bóvedas de asteroides para flotas mineras. Cuando las tripulaciones callaron, la cabeza excavadora eligió sus propias presas. Ahora rompe cascos con anchas mandíbulas rojas y gira bruscamente tras cada pasada aparentemente torpe.','Tras los ganchos amplios llegan eslalones rápidos. Deja pasar la cabeza pesada antes de cruzar su cuerpo más corto.'],
 ['Mantis Coil escapó de un criadero de máquinas quirúrgicas. Sus guadañas debían salvar naves dañadas; el Enjambre invirtió la orden. Ahora interpreta cada luz móvil como una incisión y cose elegantes cruces sobre el campo de batalla.','Vigila la cabeza durante el eslalon. El fuego sostenido sobre segmentos que regresan es más seguro que perseguir sus giros.'],
 ['Sunforge Wyrm transporta el corazón robado de una fundición estelar. Su corona dorada concentraba luz solar sobre cascos incompletos. Cada órbita alimenta ahora una boca de horno; los antiguos obreros reconocen su respiración en el calor de sus receptores.','La órbita amplia se convierte en una espiral cerrada. Ataca desde fuera y cambia de carril antes de que el cuerpo lo cierre.'],
 ['Obsidian Sawtooth se construyó con las cortadoras que desmontaron la primera prisión de Cabinet. Devoró las puertas antes de que escaparan los presos. Cuchillas negras rechinan sobre su columna, cambiando de rumbo como si buscaran otra cerradura.','Los barridos angulares se mezclan con nuevas rutas. Observa la cabeza y evita perseguirla entre sus segmentos dentados.'],
 ['Pearl Lamprey vivía bajo el hielo de una luna de repostaje abandonada. Los chatarreros siguieron su señuelo azul hasta un depósito convertido en boca. Su armadura nacarada oculta refrigeración robada; las mandíbulas circulares beben luz de motores mientras el cuerpo se enrosca.','Evita la espiral cerrada y dispara a sus numerosos segmentos. El señuelo brillante pertenece a la cabeza: no es un objeto recogible.'],
 ['Copper Tempest anidó en una instalación que capturaba tormentas. Los técnicos oyeron truenos en radios desconectadas. Sus cuernos ramificados recogen cargas de los restos, mientras el cuerpo inquieto cose trayectorias de relámpagos rotos por el espacio.','Los eslalones rápidos se vuelven barridos amplios. Observa el anillo de carga antes de la salva dirigida y abandona la línea de tiro.'],
 ['Amethyst Oracle apareció en un motor predictivo que anunció la pérdida de su propia tripulación. Tres ojos cristalinos siguieron encendidos tras apagarlo. El Enjambre les dio una columna y comenzaron a dibujar futuros que terminaban con una nave entre sus mandíbulas.','No esperes en el centro del ocho. La siguiente ruta entra suavemente; aprovecha esa transición para cambiar de carril.'],
 ['Carrion Procession sigue antiguas rutas de salvamento con catorce cámaras oxidadas tras el cráneo. Cada una fue un dron de rescate. Sus señales siguen funcionando, pero la procesión solo responde cuando algo cercano está muriendo.','El cuerpo más largo puede cerrar varios carriles. Destruye segmentos expuestos desde fuera y conserva una retirada despejada.'],
 ['Eclipse Dragon surgió cuando un escudo solar no volvió a abrirse tras una noche artificial. La corona blanca refleja estrellas y la garganta absorbe su luz. Los operarios desaparecidos sobreviven como un ritmo en su enorme respiración, justo antes de que gire.','La gran cabeza encadena ganchos, órbitas y cruces. Respeta los cambios de ruta; destruirla no elimina la columna restante.']
 ],
 'pt-BR':[
 ['Grave Eel nasceu nas barcaças funerárias de uma colônia desaparecida. O Enxame enfiou suas placas memoriais num cabo vivo e o ensinou a seguir pedidos de socorro. O crânio pálido não lembra nenhum piloto, mas a longa coluna ainda carrega seus nomes.','O corpo fino alterna varreduras largas e cruzamentos fechados. Atire ao longo dos segmentos e mantenha uma saída lateral.'],
 ['Crimson Hammer abria cofres de asteroides para frotas mineradoras. Quando as tripulações silenciaram, a cabeça escavadora escolheu suas próprias presas. Agora rompe cascos com largas mandíbulas vermelhas e vira bruscamente após cada passagem aparentemente desajeitada.','Ganchos largos dão lugar a zigue-zagues rápidos. Deixe a cabeça pesada passar antes de cruzar o corpo mais curto.'],
 ['Mantis Coil fugiu de um berçário de máquinas cirúrgicas. Suas foices deveriam salvar naves danificadas; o Enxame inverteu a ordem. Agora trata cada luz em movimento como uma incisão e costura cruzamentos elegantes pelo campo de batalha.','Observe a cabeça durante os zigue-zagues. Fogo contínuo nos segmentos que retornam é mais seguro que perseguir as curvas.'],
 ['Sunforge Wyrm carrega o coração roubado de uma fundição estelar. Sua coroa dourada concentrava luz solar em cascos inacabados. Cada órbita agora alimenta uma boca de fornalha; antigos operários reconhecem sua respiração no calor dos receptores.','A órbita larga vira uma espiral fechada. Ataque por fora e mude de faixa antes que o corpo a bloqueie.'],
 ['Obsidian Sawtooth foi montado com cortadores que desmontaram a primeira prisão de Cabinet. Engoliu as portas antes que os presos escapassem. Lâminas negras rangem pela coluna e mudam de direção como se procurassem outra fechadura.','As passagens angulares se misturam a novas rotas. Observe a cabeça e não a persiga entre os segmentos serrilhados.'],
 ['Pearl Lamprey vivia sob o gelo de uma lua de abastecimento abandonada. Sucateiros seguiram sua isca azul até um reservatório transformado em boca. A armadura nacarada esconde refrigeração roubada; mandíbulas circulares bebem luz dos motores enquanto o corpo se enrola.','Evite a espiral fechada e atire nos muitos segmentos. A isca luminosa faz parte da cabeça, não é um item coletável.'],
 ['Copper Tempest fez ninho numa estação que colhia tempestades. Técnicos ouviram trovões em rádios desconectados. Seus chifres ramificados recolhem carga dos destroços, enquanto o corpo inquieto costura caminhos de relâmpagos partidos no espaço.','Zigue-zagues rápidos viram passagens largas. Observe o anel de carga antes da salva dirigida e saia da linha de tiro.'],
 ['Amethyst Oracle foi encontrado num motor de previsão que anunciou a perda da própria tripulação. Três olhos de cristal continuaram acesos após o desligamento. O Enxame deu a eles uma coluna; desde então, todo futuro termina com uma nave entre suas mandíbulas.','Não espere no centro do oito. A próxima rota entra suavemente; aproveite a transição para mudar de faixa.'],
 ['Carrion Procession segue antigas rotas de resgate com catorze câmaras enferrujadas atrás do crânio. Cada uma já foi um drone de recuperação. Os sinais ainda funcionam, mas a procissão só responde quando algo próximo está morrendo.','O corpo mais longo pode bloquear várias faixas. Destrua segmentos expostos por fora e preserve uma retirada livre.'],
 ['Eclipse Dragon surgiu quando um escudo solar não reabriu após uma noite artificial. A coroa branca reflete estrelas e a garganta absorve sua luz. Os operadores desaparecidos sobrevivem como um ritmo na respiração imensa, ouvido pouco antes da curva.','A cabeça grande conduz ganchos, órbitas e cruzamentos. Respeite as mudanças de rota; destruir a cabeça não elimina o restante da coluna.']
 ],
 ru:[
 ['Grave Eel родился на погребальных баржах исчезнувшей колонии. Рой нанизал памятные таблички на живой кабель и научил его следовать сигналам бедствия. Бледный череп не помнит пилотов, но длинная цепь позвонков до сих пор носит их имена.','Тонкое тело меняет широкие дуги на тесные пересечения. Стреляй вдоль цепи и сохраняй путь отхода сбоку.'],
 ['Crimson Hammer вскрывал астероидные хранилища для шахтёрских флотилий. Когда экипажи замолчали, буровая голова сама выбрала добычу. Теперь широкие красные челюсти ломают корпуса, а за каждой неуклюжей на вид атакой следует резкий поворот.','За широкими крюками следуют быстрые зигзаги. Пропусти тяжёлую голову, прежде чем пересекать короткое тело.'],
 ['Mantis Coil сбежал из питомника хирургических машин. Его косы должны были спасать повреждённые корабли; Рой перевернул приказ. Теперь каждый движущийся огонь кажется ему разрезом, и он прошивает поле боя изящными пересечениями.','Следи за головой с косами во время зигзагов. Постоянный огонь по возвращающимся секциям безопаснее погони за поворотами.'],
 ['Sunforge Wyrm несёт украденное сердце звёздной кузницы. Его золотая корона когда-то направляла солнечный свет на незаконченные корпуса. Теперь каждый виток питает пасть-печь, а бывшие рабочие узнают его дыхание по жару в приёмниках.','Широкая орбита постепенно превращается в тесную петлю. Атакуй снаружи и меняй полосу, пока тело не закрыло проход.'],
 ['Obsidian Sawtooth собран из резаков, разбиравших первую тюрьму Cabinet. Он проглотил двери прежде, чем узники успели выйти. Чёрные лезвия скрежещут вдоль позвоночника и меняют направление, словно ищут звук нового замка.','Угловатые проходы переходят в новые маршруты. Следи за головой и не гонись между зубчатыми секциями.'],
 ['Pearl Lamprey жил подо льдом заброшенной заправочной луны. Сборщики лома последовали за голубой приманкой в резервуар, ставший пастью. Перламутровая броня скрывает украденное охлаждение; кольцевые челюсти пьют свет двигателей, пока тело извивается следом.','Избегай тесной петли и стреляй по многочисленным секциям. Светящаяся приманка принадлежит голове, это не предмет для подбора.'],
 ['Copper Tempest поселился в установке для сбора энергии бурь. Ремонтники слышали гром из отключённых радиостанций. Ветвистые рога собирают заряд из обломков, а беспокойное тело сшивает в космосе разорванные пути молний.','Быстрые зигзаги сменяются широкими дугами. Следи за кольцом заряда перед прицельным залпом и покидай линию огня.'],
 ['Amethyst Oracle нашли в машине предсказаний, объявившей гибель собственного экипажа. Три кристальных глаза горели после отключения. Рой дал им позвоночник; с тех пор каждая начертанная ими будущая дорога заканчивается кораблём в пасти.','Не жди в центре восьмёрки. Следующий маршрут появляется плавно; используй переход для смены полосы.'],
 ['Carrion Procession идёт по старым спасательным трассам, волоча за черепом четырнадцать ржавых камер. Каждая была ремонтным дроном. Их сигналы помощи ещё работают, но процессия отвечает лишь тогда, когда рядом что-то умирает.','Самое длинное тело перекрывает несколько полос. Уничтожай открытые секции снаружи и сохраняй свободный путь назад.'],
 ['Eclipse Dragon появился, когда солнечный щит не открылся после искусственной ночи. Белая корона отражает звёзды, а горло поглощает их свет. Пропавшие операторы остались лишь ритмом в его огромном дыхании, слышном перед поворотом.','Большая голова ведёт крюки, круги и пересечения. Учитывай смену маршрута; уничтожение головы не убивает оставшийся позвоночник.']
 ],
 'zh-CN':[
 ['Grave Eel诞生于一座失落殖民地的葬船。虫群将纪念死者的铭牌串在活体缆线上，教它追踪求救信号。苍白的头骨早已不记得任何飞行员，但漫长的脊椎仍刻着他们的名字。每当新的信号响起，那些铭牌便开始颤动，仿佛又一次等待归航。','细长身体会从大幅摆动转入紧密交叉。沿身体持续射击，并保留侧向逃生路线。'],
 ['Crimson Hammer曾为采矿舰队撬开小行星矿库。船员失去音讯后，巨大的开采头开始自行挑选目标。如今它用宽阔的红色双颚击碎船体，每次看似笨拙的掠过之后都会突然转向。残存的矿业记录仍把这种攻击称为正常的开采作业。','宽大的钩形转弯之后会接快速蛇行。先让沉重的头部通过，再穿越较短的身体。'],
 ['Mantis Coil逃出了一座培育外科机器的巢室。成对的镰刀原本用于抢救受损飞船，虫群却颠倒了命令。如今每一道移动的光都被它当成切口，优美的交叉航迹则成了缝合线。那些昔日用于救援的动作，已经变成猎杀的舞步。','蛇行时留意镰刀状头部。持续攻击折返的身体，比追赶它的快速转向更安全。'],
 ['Sunforge Wyrm携带着从恒星铸造厂偷来的核心。它的金色冠冕曾将阳光汇聚在尚未完工的船壳上。如今每一次盘旋都为熔炉巨口供能，而逃亡的工人仍能从接收器传来的灼热噪声中认出它的呼吸。那座工厂再也没有完成任何一艘飞船。','宽阔的环绕会逐渐变成收紧的盘旋。从弯道外侧攻击，在身体封路前及时换道。'],
 ['Obsidian Sawtooth由拆解Cabinet第一座监狱的切割机组成。囚犯尚未来得及逃走，它就吞掉了所有大门。黑色锯刃如今沿着脊椎相互摩擦，不断改变方向，仿佛正在寻找另一把锁的声音。监狱早已消失，拆解命令却从未结束。','棱角分明的横扫会过渡到不同路线。观察头部，不要追进锯齿般的身体间隙。'],
 ['Pearl Lamprey曾藏在废弃补给卫星的冰层下。打捞者追随蓝色诱饵，进入了已经变成巨口的储液池。珍珠色装甲内藏着偷来的冷却系统，圆环状双颚吸食引擎的光，漫长身体则在后方盘绕。卫星最后的记录只留下了越来越亮的蓝色。','避开紧密盘旋，持续攻击众多身体节段。明亮诱饵属于头部，并不是可以拾取的奖励。'],
 ['Copper Tempest在一座风暴采能阵列中筑巢。第一支维修队从断开的无线电里听见雷声。它分叉的犄角如今从残骸中收集电荷，不安分的身体在太空中缝合破碎的闪电轨迹。阵列已经停机，但那些不应存在的雷声仍在追逐来访者。','快速蛇行会转为大幅横扫。瞄准齐射前会出现蓄能环，看到后及时离开射击线。'],
 ['Amethyst Oracle出现在一台预言自身船员失踪的预测引擎中。系统关闭后，三只晶体眼睛仍然亮着。虫群为它们装上脊椎，于是它开始勾画新的未来，而每个未来的终点都是一艘落入巨颚的飞船。幸存者再也不敢询问下一次预测。','不要停在八字路线中心。下一条路线会平滑接入，利用转变的时机换到安全航道。'],
 ['Carrion Procession沿最古老的打捞航道前行，头骨后拖着十四节锈蚀舱室。每一节曾经都是回收无人机。求救信号仍然有效，但如今只有附近生命正在消逝时，这支队伍才会回应。它从不把找到的幸存者送回家，只会继续增长。','最长的身体能封住多条航道。从外侧攻击暴露节段，并始终保留清晰的撤退路线。'],
 ['Eclipse Dragon出现于一次人造黑夜之后：遮阳盾再也没有开启。白色冠冕反射星光，喉咙却将光线吞噬。失踪的操作员只剩下它庞大呼吸中的节奏，每次转向之前都能听见。无人知道他们是在警告来者，还是在为下一次吞噬计数。','巨大头部带出钩形、环绕和交叉路线。留意路线变化，摧毁头部并不能杀死剩余脊椎。']
 ],
 ko:[
 ['Grave Eel은 사라진 식민지의 장례선에서 태어났다. 군체는 추모 명판을 살아 있는 케이블에 꿰고 구조 신호를 추적하도록 가르쳤다. 창백한 두개골은 조종사를 기억하지 못하지만, 긴 척추에는 아직 그들의 이름이 남아 있다.','가느다란 몸이 넓은 곡선과 좁은 교차로를 오간다. 몸을 따라 사격하며 옆으로 빠질 길을 남겨 두자.'],
 ['Crimson Hammer는 광산 함대의 소행성 금고를 열었다. 승무원이 응답하지 않자 굴착 머리가 스스로 먹잇감을 골랐다. 이제 넓고 붉은 턱으로 선체를 부수며, 둔해 보이는 통과 뒤에 갑자기 방향을 바꾼다.','넓은 갈고리 회전 뒤에는 빠른 지그재그가 온다. 무거운 머리가 지나간 뒤 짧은 몸을 가로지르자.'],
 ['Mantis Coil은 수술 기계를 기르던 시설에서 탈출했다. 한 쌍의 낫은 손상된 함선을 구하도록 설계됐지만 군체가 명령을 뒤집었다. 이제 움직이는 모든 빛을 절개선으로 여기며 전장에 우아한 교차선을 꿰맨다.','지그재그 중에는 갈고리 머리를 지켜보자. 빠른 회전을 쫓기보다 돌아오는 몸에 지속 사격하는 편이 안전하다.'],
 ['Sunforge Wyrm은 항성 주조소에서 훔친 심장을 품고 있다. 황금 왕관은 미완성 선체에 햇빛을 집중하던 장치였다. 이제 매번 선회할 때마다 용광로 입을 먹여 살리며, 옛 노동자들은 수신기를 태우는 열기에서 그 숨소리를 알아본다.','넓은 선회가 점차 좁은 똬리로 바뀐다. 곡선 바깥에서 공격하고 몸이 길을 막기 전에 이동하자.'],
 ['Obsidian Sawtooth는 Cabinet 최초의 감옥을 해체하던 절단기로 만들어졌다. 죄수들이 나가기 전에 문을 삼켰다. 검은 칼날들이 척추를 따라 갈리며 방향을 바꾸는 모습은 또 다른 자물쇠 소리를 찾는 듯하다.','각진 이동이 다른 경로로 이어진다. 머리 움직임을 읽고 톱니 모양 몸 사이로 쫓아 들어가지 말자.'],
 ['Pearl Lamprey는 버려진 연료 위성의 얼음 아래 살았다. 인양대는 푸른 미끼를 따라 입으로 변한 저장고에 들어갔다. 진주빛 갑옷 아래에는 훔친 냉각 장치가 있으며, 원형 턱이 엔진 빛을 마시는 동안 긴 몸이 뒤에서 감긴다.','좁은 똬리를 피하며 많은 몸마디를 사격하자. 밝은 미끼는 머리의 일부이며 획득 아이템이 아니다.'],
 ['Copper Tempest는 폭풍 채집 시설에 둥지를 틀었다. 수리대는 연결이 끊긴 무전기에서 천둥을 들었다. 갈라진 뿔은 잔해에서 전하를 모으고, 불안하게 움직이는 몸은 우주에 부서진 번개 경로를 꿰맨다.','빠른 지그재그가 넓은 곡선으로 바뀐다. 조준 일제사격 전의 충전 고리를 보고 사격선에서 벗어나자.'],
 ['Amethyst Oracle은 자기 승무원의 실종을 예언한 예측 장치에서 발견됐다. 전원을 꺼도 세 수정 눈은 빛났다. 군체가 눈에 척추를 붙이자, 그것은 언제나 턱 속의 함선으로 끝나는 미래를 그리기 시작했다.','팔자 경로의 중앙에 머물지 말자. 다음 경로가 부드럽게 이어지는 동안 안전한 차선으로 바꾸자.'],
 ['Carrion Procession은 두개골 뒤에 녹슨 방 열네 개를 끌며 오래된 인양 항로를 따른다. 각 방은 한때 구조 드론이었다. 구조 신호는 아직 작동하지만, 이제 이 행렬은 근처의 무언가가 죽어 갈 때만 응답한다.','가장 긴 몸은 여러 길을 막을 수 있다. 바깥에서 노출된 마디를 공격하고 명확한 후퇴로를 확보하자.'],
 ['Eclipse Dragon은 인공 밤이 끝나도 태양 차폐막이 열리지 않았을 때 나타났다. 흰 왕관은 별빛을 반사하고 목구멍은 삼킨다. 사라진 운용자들은 방향 전환 직전에 들리는 거대한 숨결의 박자로만 남아 있다.','큰 머리가 갈고리, 선회, 교차 경로를 이끈다. 경로 변화를 주시하자. 머리를 파괴해도 남은 척추는 살아 있다.']
 ],
 ja:[
 ['Grave Eelは消えた植民地の葬送船で生まれた。スウォームは追悼の銘板を生きたケーブルに通し、救難信号を追うよう教えた。白い頭骨は操縦士を覚えていないが、長い椎骨の列には今も名前が残っている。','細い胴体は大きな弧から狭い交差へ移る。胴に沿って撃ち、横へ逃げる道を残そう。'],
 ['Crimson Hammerは採掘船団のために小惑星の金庫を開けていた。乗員が応答しなくなると掘削頭部が自ら獲物を選んだ。今は幅広い赤い顎で船体を砕き、不器用に見える通過の直後に鋭く折り返す。','大きな鉤状旋回の後は素早い蛇行が来る。重い頭が通過してから短い胴体を横切ろう。'],
 ['Mantis Coilは外科機械を育てる施設から逃げた。一対の鎌は損傷船を救うためのものだったが、スウォームが命令を反転させた。今は動く光をすべて切開線と見なし、戦場に優雅な交差を縫いつける。','蛇行中は鎌のある頭を見よう。急旋回を追うより、戻ってくる節への持続射撃が安全だ。'],
 ['Sunforge Wyrmは恒星鋳造所から盗んだ心臓を運ぶ。金の冠は未完成の船殻に日光を集めていた。今は旋回するたび炉の口に力を送り、元作業員は受信機を焼く熱にその呼吸を聞き分ける。','大きな周回が徐々に狭いとぐろへ変わる。曲線の外から攻撃し、胴体に塞がれる前に移動しよう。'],
 ['Obsidian SawtoothはCabinet最初の牢獄を解体した切断機から作られた。囚人が出る前に扉を飲み込んだ。黒い刃は背骨に沿って軋み、別の錠の音を探すかのように向きを変え続ける。','角張った掃引は別の経路へ移る。頭の動きを読み、鋸刃状の節の間へ追い込まれないようにしよう。'],
 ['Pearl Lampreyは廃棄された補給衛星の氷の下に住んでいた。回収隊は青い誘い灯を追い、口となった貯蔵槽へ入った。真珠色の装甲には盗んだ冷却装置があり、円い顎がエンジン光を飲む間に長い胴が巻きつく。','狭いとぐろを避け、多数の節を撃とう。明るい誘い灯は頭の一部で、回収アイテムではない。'],
 ['Copper Tempestは嵐の採取装置に巣を作った。修理隊は切断した無線から雷を聞いた。枝分かれした角は残骸から電荷を集め、落ち着かない胴体が宇宙に壊れた稲妻の道を縫い合わせる。','速い蛇行は広い弧へ変わる。狙い撃ちの前の充電リングを見て、射線から離れよう。'],
 ['Amethyst Oracleは自らの乗員喪失を予告した予測機関で発見された。停止しても三つの水晶眼は光り続けた。スウォームが背骨を与えると、顎の中の船で終わる未来ばかりを描くようになった。','八の字の中心で待たないこと。次の経路が滑らかにつながる移行中に、安全なレーンへ移ろう。'],
 ['Carrion Processionは頭骨の後ろに十四の錆びた部屋を鳴らし、古い回収航路を進む。各部屋はかつて救助ドローンだった。救難信号は今も動くが、行列が答えるのは近くで何かが死にかけた時だけだ。','最長の胴体は複数の道を塞ぐ。外側から露出した節を壊し、明確な退路を確保しよう。'],
 ['Eclipse Dragonは人工の夜が終わっても太陽遮蔽板が開かなかった時に現れた。白い冠は星明かりを反射し、喉はそれを吸う。消えた操作者たちは、旋回の直前に聞こえる巨大な呼吸の拍子にだけ残っている。','大きな頭が鉤、周回、交差を導く。経路の変化を尊重しよう。頭を壊しても残った背骨は生きている。']
 ]
};
export function getExpandedSnakeText(index,locale='en'){
 const row=(entries[locale]||entries.en)[index-4];if(!row)return null;
 return {name:names[index-4],description:row[0],tip:row[1]};
}
