const COMMON_FORMS = ['GRID', 'STAGGERED_WING', 'DOUBLE_ARC', 'PINCER', 'CROSS_STREAM', 'SCREEN_DOOR'];
const ARC_FORMS = ['SIDEWINDER', 'SPIRAL', 'CROSS_STREAM', 'DIAGONAL_RAID'];
const DENIAL_FORMS = ['SCREEN_DOOR', 'ORBIT_RING', 'GRID', 'BOX'];

export const ENEMY_THREAT_ACTION_VARIANTS = Object.freeze([
  {
    id: 'ion_pin_lance',
    label: 'Ion Pin Lance',
    handlerId: 'telegraph_rail_lance',
    minLevel: 4,
    tags: ['rail', 'precision', 'ion'],
    roleTags: ['sniper', 'simple_shooter'],
    telegraphMs: 820,
    cooldownMs: 11200,
    maxActivePerWave: 1,
    dangerBudgetCost: 2,
    weight: 0.72,
    preferredFormations: ['DIAGONAL_RAID', 'CROSS_STREAM'],
    preferredTactics: ['needle_stagger', 'rush_feint'],
    compatibleMovementStyles: ['needle', 'anchor', 'pincer'],
    compatibleFireStyles: ['needle', 'laneShot', 'warningShot'],
    weaponId: 'cyan_rail_needle',
    telegraph: 'line',
    codexTip: 'The ion pin is polite enough to draw a ruler. Leave the ruler before the beam signs it.'
  },
  {
    id: 'blueprint_lance',
    label: 'Blueprint Lance',
    handlerId: 'telegraph_rail_lance',
    minLevel: 9,
    tags: ['rail', 'architect', 'locked_target'],
    roleTags: ['sniper', 'formation_anchor'],
    telegraphMs: 760,
    cooldownMs: 11800,
    maxActivePerWave: 1,
    dangerBudgetCost: 2,
    weight: 0.66,
    preferredFormations: ['GRID', 'SCREEN_DOOR', 'PINCER'],
    preferredTactics: ['weave_wall', 'crossfire_pincer'],
    compatibleMovementStyles: ['anchor', 'weave_wall', 'needle'],
    compatibleFireStyles: ['laneShot', 'suppressiveLine', 'warningShot'],
    weaponId: 'white_comet_lance',
    telegraph: 'line',
    codexTip: 'It locks a future version of your lane. Refuse the paperwork and sidestep after lock.'
  },
  {
    id: 'prism_verdict',
    label: 'Prism Verdict',
    handlerId: 'telegraph_rail_lance',
    minLevel: 15,
    tags: ['rail', 'rare', 'prism'],
    roleTags: ['disruptor', 'sniper'],
    telegraphMs: 690,
    cooldownMs: 12600,
    maxActivePerWave: 1,
    dangerBudgetCost: 3,
    weight: 0.48,
    preferredFormations: ['CROSS_STREAM', 'SPIRAL'],
    preferredTactics: ['ambush_lattice', 'needle_stagger'],
    compatibleMovementStyles: ['ambush', 'needle', 'split_sweep'],
    compatibleFireStyles: ['predictiveShot', 'laneShot', 'needle'],
    weaponId: 'purple_boss_spear',
    telegraph: 'line',
    codexTip: 'The prism judges where you were drifting, not where you wish you were. Break the habit.'
  },
  {
    id: 'turnstile_cutter',
    label: 'Turnstile Cutter',
    handlerId: 'lane_cutter',
    minLevel: 3,
    tags: ['lane', 'gate', 'traffic'],
    roleTags: ['space_denial', 'formation_anchor'],
    telegraphMs: 720,
    cooldownMs: 9800,
    maxActivePerWave: 1,
    dangerBudgetCost: 2,
    weight: 0.84,
    preferredFormations: ['SCREEN_DOOR', 'GRID', 'PINCER'],
    preferredTactics: ['weave_wall', 'pulse_net'],
    compatibleMovementStyles: ['weave_wall', 'anchor', 'pincer'],
    compatibleFireStyles: ['laneShot', 'suppressiveLine'],
    weaponId: 'white_comet_lance',
    telegraph: 'lane',
    codexTip: 'Treat the lit lane like a subway door. Commit early or let it close.'
  },
  {
    id: 'neon_tax_lane',
    label: 'Neon Tax Lane',
    handlerId: 'lane_cutter',
    minLevel: 7,
    tags: ['lane', 'economy', 'pressure'],
    roleTags: ['sniper', 'space_denial'],
    telegraphMs: 640,
    cooldownMs: 10300,
    maxActivePerWave: 1,
    dangerBudgetCost: 2,
    weight: 0.72,
    preferredFormations: ['CROSS_STREAM', 'DIAGONAL_RAID'],
    preferredTactics: ['crossfire_pincer', 'rush_feint'],
    compatibleMovementStyles: ['pincer', 'feint', 'needle'],
    compatibleFireStyles: ['laneShot', 'warningShot'],
    weaponId: 'teal_fork_dart',
    telegraph: 'lane',
    codexTip: 'This lane charges interest. Cross before the bill arrives.'
  },
  {
    id: 'closing_argument',
    label: 'Closing Argument',
    handlerId: 'lane_cutter',
    minLevel: 18,
    tags: ['lane', 'climax', 'legal'],
    roleTags: ['disruptor', 'formation_anchor'],
    telegraphMs: 590,
    cooldownMs: 11600,
    maxActivePerWave: 1,
    dangerBudgetCost: 3,
    weight: 0.5,
    preferredFormations: ['SCREEN_DOOR', 'CROSS_STREAM', 'PINCER'],
    preferredTactics: ['ambush_lattice', 'weave_wall'],
    compatibleMovementStyles: ['ambush', 'weave_wall', 'pincer'],
    compatibleFireStyles: ['suppressiveLine', 'laneShot', 'predictiveShot'],
    weaponId: 'orange_molten_slug',
    telegraph: 'lane',
    codexTip: 'If the swarm is making a closing argument, stop standing in the evidence.'
  },
  {
    id: 'seed_of_regret',
    label: 'Seed of Regret',
    handlerId: 'splitter_seed',
    minLevel: 2,
    tags: ['fragment', 'delayed', 'botany'],
    roleTags: ['basic_fodder', 'simple_shooter', 'space_denial'],
    telegraphMs: 600,
    cooldownMs: 8200,
    maxActivePerWave: 2,
    dangerBudgetCost: 1,
    weight: 0.96,
    preferredFormations: COMMON_FORMS,
    preferredTactics: ['needle_stagger', 'pulse_net'],
    compatibleMovementStyles: ['sine', 'chain', 'pulse', 'standard'],
    compatibleFireStyles: ['splitLite', 'slowOrb', 'single'],
    weaponId: 'toxic_splinter_seed',
    telegraph: 'ring',
    codexTip: 'Do not argue with the seed. Wait for the bloom, then pass through the apology gap.'
  },
  {
    id: 'confetti_grenade',
    label: 'Confetti Grenade',
    handlerId: 'splitter_seed',
    minLevel: 6,
    tags: ['fragment', 'party', 'delayed'],
    roleTags: ['spread_shooter', 'disruptor'],
    telegraphMs: 540,
    cooldownMs: 8600,
    maxActivePerWave: 2,
    dangerBudgetCost: 1,
    weight: 0.78,
    preferredFormations: ['DOUBLE_ARC', 'SPIRAL', 'STAGGERED_WING'],
    preferredTactics: ['split_sweep', 'pulse_net'],
    compatibleMovementStyles: ['split_sweep', 'sweep', 'pulse'],
    compatibleFireStyles: ['splitLite', 'fanPulse', 'forkShot'],
    weaponId: 'pink_spiral_disruptor',
    telegraph: 'ring',
    codexTip: 'It celebrates before it hurts you. Let the party pop, then move through the quiet slice.'
  },
  {
    id: 'hush_pod',
    label: 'Hush Pod',
    handlerId: 'splitter_seed',
    minLevel: 13,
    tags: ['fragment', 'quiet', 'rare'],
    roleTags: ['disruptor', 'space_denial'],
    telegraphMs: 500,
    cooldownMs: 9400,
    maxActivePerWave: 2,
    dangerBudgetCost: 2,
    weight: 0.58,
    preferredFormations: ['BOX', 'SCREEN_DOOR', 'ORBIT_RING'],
    preferredTactics: ['ambush_lattice', 'orbit_snare'],
    compatibleMovementStyles: ['ambush', 'orbit', 'weave_wall'],
    compatibleFireStyles: ['slowOrb', 'chargeShot', 'splitLite'],
    weaponId: 'amber_plasma_orb',
    telegraph: 'ring',
    codexTip: 'The quiet pod is never quiet for your benefit. Make space before it opens.'
  },
  {
    id: 'parking_violation',
    label: 'Parking Violation',
    handlerId: 'mine_drop',
    minLevel: 3,
    tags: ['mine', 'space_denial', 'comic'],
    roleTags: ['space_denial', 'slow_tank'],
    telegraphMs: 650,
    cooldownMs: 10800,
    maxActivePerWave: 1,
    dangerBudgetCost: 2,
    activeBulletCap: 4,
    weight: 0.82,
    preferredFormations: DENIAL_FORMS,
    preferredTactics: ['weave_wall', 'orbit_snare'],
    compatibleMovementStyles: ['weave_wall', 'anchor', 'orbit'],
    compatibleFireStyles: ['slowOrb', 'slowHeavy'],
    weaponId: 'violet_star_mine',
    telegraph: 'ring',
    codexTip: 'The mine owns the lane only if you let it finish parking.'
  },
  {
    id: 'sleepy_satchel',
    label: 'Sleepy Satchel',
    handlerId: 'mine_drop',
    minLevel: 8,
    tags: ['mine', 'delay', 'space_denial'],
    roleTags: ['formation_anchor', 'space_denial'],
    telegraphMs: 600,
    cooldownMs: 11200,
    maxActivePerWave: 1,
    dangerBudgetCost: 2,
    activeBulletCap: 4,
    weight: 0.68,
    preferredFormations: ['ORBIT_RING', 'GRID', 'SCREEN_DOOR'],
    preferredTactics: ['pulse_net', 'orbit_snare'],
    compatibleMovementStyles: ['orbit', 'pulse', 'anchor'],
    compatibleFireStyles: ['slowOrb', 'warningShot', 'chargeShot'],
    weaponId: 'lime_saw_disc',
    telegraph: 'ring',
    codexTip: 'Sleepy does not mean harmless. It means the explosion is doing stretches.'
  },
  {
    id: 'hazard_receipt',
    label: 'Hazard Receipt',
    handlerId: 'mine_drop',
    minLevel: 17,
    tags: ['mine', 'rare', 'climax'],
    roleTags: ['disruptor', 'elite_tactical'],
    telegraphMs: 560,
    cooldownMs: 12200,
    maxActivePerWave: 1,
    dangerBudgetCost: 3,
    activeBulletCap: 5,
    weight: 0.46,
    preferredFormations: ['SCREEN_DOOR', 'CROSS_STREAM', 'SPIRAL'],
    preferredTactics: ['ambush_lattice', 'weave_wall'],
    compatibleMovementStyles: ['ambush', 'split_sweep', 'weave_wall'],
    compatibleFireStyles: ['chargeShot', 'suppressiveLine', 'slowHeavy'],
    weaponId: 'orange_molten_slug',
    telegraph: 'ring',
    codexTip: 'If you can read the receipt, you are close enough to return the item.'
  },
  {
    id: 'pocket_supernova',
    label: 'Pocket Supernova',
    handlerId: 'pulse_ring_bloom',
    minLevel: 4,
    tags: ['space_pattern', 'ring', 'solar'],
    roleTags: ['formation_anchor', 'simple_shooter'],
    telegraphMs: 650,
    cooldownMs: 8800,
    maxActivePerWave: 1,
    dangerBudgetCost: 1,
    weight: 0.9,
    preferredFormations: ['ORBIT_RING', 'GRID', 'SPIRAL'],
    preferredTactics: ['pulse_net', 'orbit_snare'],
    compatibleMovementStyles: ['orbit', 'pulse', 'anchor'],
    compatibleFireStyles: ['fanPulse', 'rotatingPair', 'slowOrb'],
    weaponId: 'lime_saw_disc',
    telegraph: 'ring',
    codexTip: 'The ring is a clock with teeth. Move once through the missing tooth.'
  },
  {
    id: 'halo_tax',
    label: 'Halo Tax',
    handlerId: 'pulse_ring_bloom',
    minLevel: 10,
    tags: ['space_pattern', 'ring', 'economy'],
    roleTags: ['escort', 'formation_anchor'],
    telegraphMs: 590,
    cooldownMs: 9300,
    maxActivePerWave: 1,
    dangerBudgetCost: 2,
    weight: 0.62,
    preferredFormations: ['DOUBLE_ARC', 'ORBIT_RING', 'CROSS_STREAM'],
    preferredTactics: ['pulse_net', 'split_sweep'],
    compatibleMovementStyles: ['orbit', 'split_sweep', 'sweep'],
    compatibleFireStyles: ['fanPulse', 'rotatingPair', 'triad'],
    weaponId: 'purple_boss_spear',
    telegraph: 'ring',
    codexTip: 'Do not pay the halo tax twice. Pick a gap and stop overcorrecting.'
  },
  {
    id: 'crown_bloom',
    label: 'Crown Bloom',
    handlerId: 'pulse_ring_bloom',
    minLevel: 20,
    tags: ['space_pattern', 'rare', 'crown'],
    roleTags: ['elite_tactical', 'disruptor'],
    telegraphMs: 540,
    cooldownMs: 10600,
    maxActivePerWave: 1,
    dangerBudgetCost: 3,
    weight: 0.42,
    preferredFormations: ['SPIRAL', 'ORBIT_RING', 'SCREEN_DOOR'],
    preferredTactics: ['ambush_lattice', 'orbit_snare'],
    compatibleMovementStyles: ['ambush', 'orbit', 'pulse'],
    compatibleFireStyles: ['fanPulse', 'rotatingPair', 'predictiveShot'],
    weaponId: 'pink_spiral_disruptor',
    telegraph: 'ring',
    codexTip: 'The crown opens with gaps because royalty enjoys watching pilots choose.'
  },
  {
    id: 'forklift_crossfire',
    label: 'Forklift Crossfire',
    handlerId: 'crossfire_pair',
    minLevel: 2,
    tags: ['formation', 'angled', 'starter'],
    roleTags: ['fast_scout', 'simple_shooter'],
    telegraphMs: 560,
    cooldownMs: 8200,
    maxActivePerWave: 2,
    dangerBudgetCost: 1,
    weight: 0.95,
    preferredFormations: ['PINCER', 'STAGGERED_WING', 'CROSS_STREAM'],
    preferredTactics: ['crossfire_pincer', 'strafe_sweep'],
    compatibleMovementStyles: ['pincer', 'sweep', 'chain'],
    compatibleFireStyles: ['crossShot', 'offsetPair', 'single'],
    weaponId: 'teal_fork_dart',
    telegraph: 'line',
    codexTip: 'The side ship is moving furniture into your lane. Do not help.'
  },
  {
    id: 'argument_from_both_sides',
    label: 'Argument From Both Sides',
    handlerId: 'crossfire_pair',
    minLevel: 8,
    tags: ['formation', 'angled', 'debate'],
    roleTags: ['sniper', 'spread_shooter'],
    telegraphMs: 520,
    cooldownMs: 9000,
    maxActivePerWave: 2,
    dangerBudgetCost: 2,
    weight: 0.66,
    preferredFormations: ['PINCER', 'CROSS_STREAM', 'DIAGONAL_RAID'],
    preferredTactics: ['crossfire_pincer', 'rush_feint'],
    compatibleMovementStyles: ['pincer', 'feint', 'needle'],
    compatibleFireStyles: ['crossShot', 'forkShot', 'needle'],
    weaponId: 'crimson_shard',
    telegraph: 'line',
    codexTip: 'The center lane is the moderator. It is also bait.'
  },
  {
    id: 'parallax_trial',
    label: 'Parallax Trial',
    handlerId: 'crossfire_pair',
    minLevel: 16,
    tags: ['formation', 'rare', 'parallax'],
    roleTags: ['disruptor', 'evasive'],
    telegraphMs: 470,
    cooldownMs: 9800,
    maxActivePerWave: 2,
    dangerBudgetCost: 2,
    weight: 0.44,
    preferredFormations: ['CROSS_STREAM', 'SPIRAL', 'SIDEWINDER'],
    preferredTactics: ['split_sweep', 'ambush_lattice'],
    compatibleMovementStyles: ['split_sweep', 'ambush', 'boomerang'],
    compatibleFireStyles: ['crossShot', 'arcVolley', 'predictiveShot'],
    weaponId: 'magenta_crescent',
    telegraph: 'line',
    codexTip: 'Your eyes will vote for the wrong side first. Let the crossing angle declare itself.'
  },
  {
    id: 'crescent_errand',
    label: 'Crescent Errand',
    handlerId: 'boomerang_crescent',
    minLevel: 5,
    tags: ['arc', 'trickster', 'errand'],
    roleTags: ['evasive', 'fast_scout'],
    telegraphMs: 640,
    cooldownMs: 9000,
    maxActivePerWave: 2,
    dangerBudgetCost: 1,
    weight: 0.82,
    preferredFormations: ARC_FORMS,
    preferredTactics: ['split_sweep', 'rush_feint'],
    compatibleMovementStyles: ['split_sweep', 'sweep', 'boomerang'],
    compatibleFireStyles: ['arcVolley', 'wide', 'crossShot'],
    weaponId: 'magenta_crescent',
    telegraph: 'arc',
    codexTip: 'The crescent has an errand across the screen. Let it finish somewhere else.'
  },
  {
    id: 'boomerang_invoice',
    label: 'Boomerang Invoice',
    handlerId: 'boomerang_crescent',
    minLevel: 11,
    tags: ['arc', 'return', 'economy'],
    roleTags: ['evasive', 'disruptor'],
    telegraphMs: 570,
    cooldownMs: 9400,
    maxActivePerWave: 2,
    dangerBudgetCost: 2,
    weight: 0.6,
    preferredFormations: ['SIDEWINDER', 'SPIRAL', 'CROSS_STREAM'],
    preferredTactics: ['split_sweep', 'ambush_lattice'],
    compatibleMovementStyles: ['boomerang', 'split_sweep', 'ambush'],
    compatibleFireStyles: ['arcVolley', 'rotatingPair', 'stutter'],
    weaponId: 'pink_spiral_disruptor',
    telegraph: 'arc',
    codexTip: 'It comes back because the swarm keeps receipts. Dodge the curve, not the launch.'
  },
  {
    id: 'lunar_backhand',
    label: 'Lunar Backhand',
    handlerId: 'boomerang_crescent',
    minLevel: 21,
    tags: ['arc', 'rare', 'lunar'],
    roleTags: ['elite_tactical', 'evasive'],
    telegraphMs: 520,
    cooldownMs: 10200,
    maxActivePerWave: 2,
    dangerBudgetCost: 3,
    weight: 0.38,
    preferredFormations: ['SPIRAL', 'SIDEWINDER', 'PINCER'],
    preferredTactics: ['ambush_lattice', 'split_sweep'],
    compatibleMovementStyles: ['boomerang', 'ambush', 'feint'],
    compatibleFireStyles: ['arcVolley', 'predictiveShot', 'stutter'],
    weaponId: 'purple_boss_spear',
    telegraph: 'arc',
    codexTip: 'The backhand is wider than it looks. Give the moon room to be dramatic.'
  },
  {
    id: 'hesitation_bolt',
    label: 'Hesitation Bolt',
    handlerId: 'brake_dash_bolt',
    minLevel: 4,
    tags: ['timing', 'dash', 'starter'],
    roleTags: ['fast_scout', 'charger'],
    telegraphMs: 610,
    cooldownMs: 8200,
    maxActivePerWave: 2,
    dangerBudgetCost: 1,
    weight: 0.86,
    preferredFormations: ['DIAGONAL_RAID', 'STAGGERED_WING'],
    preferredTactics: ['rush_feint', 'needle_stagger'],
    compatibleMovementStyles: ['feint', 'needle', 'sweep'],
    compatibleFireStyles: ['stutter', 'quickChip', 'needle'],
    weaponId: 'cyan_rail_needle',
    telegraph: 'line',
    codexTip: 'It pauses to make you flinch. Dodge on the flash, not the apology.'
  },
  {
    id: 'redlight_greenlight',
    label: 'Redlight Greenlight',
    handlerId: 'brake_dash_bolt',
    minLevel: 12,
    tags: ['timing', 'dash', 'game'],
    roleTags: ['charger', 'disruptor'],
    telegraphMs: 540,
    cooldownMs: 9000,
    maxActivePerWave: 2,
    dangerBudgetCost: 2,
    weight: 0.58,
    preferredFormations: ['DIAGONAL_RAID', 'PINCER', 'SIDEWINDER'],
    preferredTactics: ['rush_feint', 'split_sweep'],
    compatibleMovementStyles: ['feint', 'split_sweep', 'pulseAdvance'],
    compatibleFireStyles: ['stutter', 'predictiveShot', 'quickChip'],
    weaponId: 'orange_molten_slug',
    telegraph: 'line',
    codexTip: 'When it stops, you stop guessing. When it blinks, you move.'
  },
  {
    id: 'afterburner_receipt',
    label: 'Afterburner Receipt',
    handlerId: 'brake_dash_bolt',
    minLevel: 22,
    tags: ['timing', 'rare', 'dash'],
    roleTags: ['elite_fodder', 'charger'],
    telegraphMs: 500,
    cooldownMs: 9800,
    maxActivePerWave: 2,
    dangerBudgetCost: 3,
    weight: 0.36,
    preferredFormations: ['CROSS_STREAM', 'DIAGONAL_RAID', 'SPIRAL'],
    preferredTactics: ['ambush_lattice', 'rush_feint'],
    compatibleMovementStyles: ['ambush', 'feint', 'needle'],
    compatibleFireStyles: ['predictiveShot', 'stutter', 'needle'],
    weaponId: 'crimson_shard',
    telegraph: 'line',
    codexTip: 'This one invoices you after the dash. Do not be in the billing lane.'
  },
  {
    id: 'missing_slice_fan',
    label: 'Missing Slice Fan',
    handlerId: 'shotgun_fan_feint',
    minLevel: 6,
    tags: ['fan', 'gap', 'feint'],
    roleTags: ['spread_shooter', 'charger'],
    telegraphMs: 740,
    cooldownMs: 11200,
    maxActivePerWave: 1,
    dangerBudgetCost: 2,
    weight: 0.72,
    preferredFormations: ['DOUBLE_ARC', 'STAGGERED_WING', 'PINCER'],
    preferredTactics: ['rush_feint', 'split_sweep'],
    compatibleMovementStyles: ['feint', 'chain', 'split_sweep'],
    compatibleFireStyles: ['fan', 'fanPulse', 'forkShot'],
    weaponId: 'white_comet_lance',
    telegraph: 'cone',
    codexTip: 'The safe gap is the missing slice. Find dessert before the fan arrives.'
  },
  {
    id: 'false_curtain',
    label: 'False Curtain',
    handlerId: 'shotgun_fan_feint',
    minLevel: 14,
    tags: ['fan', 'fakeout', 'theater'],
    roleTags: ['disruptor', 'spread_shooter'],
    telegraphMs: 660,
    cooldownMs: 11800,
    maxActivePerWave: 1,
    dangerBudgetCost: 2,
    weight: 0.52,
    preferredFormations: ['PINCER', 'CROSS_STREAM', 'SPIRAL'],
    preferredTactics: ['rush_feint', 'ambush_lattice'],
    compatibleMovementStyles: ['feint', 'ambush', 'split_sweep'],
    compatibleFireStyles: ['fan', 'triad', 'predictiveShot'],
    weaponId: 'pink_spiral_disruptor',
    telegraph: 'cone',
    codexTip: 'The curtain lies, but the center line tells the truth. Hold your dodge until the reveal.'
  },
  {
    id: 'auditor_fan',
    label: 'Auditor Fan',
    handlerId: 'shotgun_fan_feint',
    minLevel: 24,
    tags: ['fan', 'rare', 'audit'],
    roleTags: ['elite_tactical', 'disruptor'],
    telegraphMs: 600,
    cooldownMs: 12800,
    maxActivePerWave: 1,
    dangerBudgetCost: 3,
    weight: 0.34,
    preferredFormations: ['SCREEN_DOOR', 'CROSS_STREAM', 'PINCER'],
    preferredTactics: ['ambush_lattice', 'weave_wall'],
    compatibleMovementStyles: ['ambush', 'weave_wall', 'feint'],
    compatibleFireStyles: ['fanPulse', 'forkShot', 'predictiveShot'],
    weaponId: 'purple_boss_spear',
    telegraph: 'cone',
    codexTip: 'The auditor checks every lane except one. Your job is to become the exception.'
  },
  {
    id: 'tiny_moons',
    label: 'Tiny Moons',
    handlerId: 'orbiting_satellites',
    minLevel: 9,
    tags: ['orbit', 'space_denial', 'satellite'],
    roleTags: ['formation_anchor', 'escort'],
    telegraphMs: 720,
    cooldownMs: 12600,
    maxActivePerWave: 1,
    dangerBudgetCost: 2,
    activeBulletCap: 6,
    weight: 0.72,
    preferredFormations: ['ORBIT_RING', 'GRID', 'SPIRAL'],
    preferredTactics: ['orbit_snare', 'pulse_net'],
    compatibleMovementStyles: ['orbit', 'anchor', 'pulse'],
    compatibleFireStyles: ['rotatingPair', 'fanPulse', 'slowOrb'],
    weaponId: 'lime_saw_disc',
    telegraph: 'ring',
    codexTip: 'Wait for the moons to leave orbit. Crossing during launch is astronomy with consequences.'
  },
  {
    id: 'paperclip_orbit',
    label: 'Paperclip Orbit',
    handlerId: 'orbiting_satellites',
    minLevel: 16,
    tags: ['orbit', 'office', 'space_denial'],
    roleTags: ['escort', 'disruptor'],
    telegraphMs: 650,
    cooldownMs: 13200,
    maxActivePerWave: 1,
    dangerBudgetCost: 2,
    activeBulletCap: 6,
    weight: 0.5,
    preferredFormations: ['ORBIT_RING', 'CROSS_STREAM', 'SCREEN_DOOR'],
    preferredTactics: ['orbit_snare', 'weave_wall'],
    compatibleMovementStyles: ['orbit', 'weave_wall', 'ambush'],
    compatibleFireStyles: ['rotatingPair', 'stutter', 'suppressiveLine'],
    weaponId: 'teal_fork_dart',
    telegraph: 'ring',
    codexTip: 'It looks helpful. It is not helpful. Let the orbit unclip before crossing.'
  },
  {
    id: 'royal_satellites',
    label: 'Royal Satellites',
    handlerId: 'orbiting_satellites',
    minLevel: 26,
    tags: ['orbit', 'rare', 'crown'],
    roleTags: ['elite_tactical', 'formation_anchor'],
    telegraphMs: 600,
    cooldownMs: 14200,
    maxActivePerWave: 1,
    dangerBudgetCost: 3,
    activeBulletCap: 7,
    weight: 0.32,
    preferredFormations: ['ORBIT_RING', 'SPIRAL', 'SCREEN_DOOR'],
    preferredTactics: ['ambush_lattice', 'orbit_snare'],
    compatibleMovementStyles: ['orbit', 'ambush', 'pulse'],
    compatibleFireStyles: ['rotatingPair', 'predictiveShot', 'fanPulse'],
    weaponId: 'purple_boss_spear',
    telegraph: 'ring',
    codexTip: 'Royal satellites launch with ceremony. Respect the ceremony, then steal the lane.'
  }
]);
