// Authored combat identities. Audio copy is English performance text, not UI/subtitles.
// Weapons, motion and damage-stage changes are deliberately independent of family.
const rows = [
  ['glass_widow','pounce','needle,braid,bomb','chitin', 'Glass Widow inbound. Watch her fangs.', 'razor glass mandibles, brittle insect clicks, predatory breath'],
  ['cinder_manta','swoop','flame,bomb,fan','wings', 'Cinder Manta. Keep clear of the furnace.', 'roaring plasma furnace, fluttering combustion, hot ceramic cracks'],
  ['needle_saint','strafe','needle,lance,needle','none', 'Needle Saint on approach. Never fly straight.', 'tense bowed titanium, hypersonic needle cracks, cold metallic whisper'],
  ['blind_leviathan','hunt','sonic,fan,charge','none', 'Blind Leviathan. It can hear you move.', 'abyssal throat barks, resonant living sonar, muscular pressure thumps'],
  ['lantern_eater','hunt','drone,homing,flame','none', 'Lantern Eater incoming. Something hungry in the dark.', 'hollow mouth suction, electric lantern chirr, deep snapping jaw'],
  ['scissor_twins','scissor','crossfire,lance,fan','twin', 'Scissor Twins. Do not let them box you in.', 'two contrasting metallic predator calls, slicing air, steel jaw snaps'],
  ['red_wake','dive','needle,charge,mines','none', 'Red Wake. Fast mover. Mind the trail.', 'furious turbine snarl, Doppler knife rush, crimson ion crackle'],
  ['foldship','swoop','broadside,lance,split','wings', 'Foldship arriving. Those wings are weapons.', 'folding alien alloy, deep torsion creak, sharp magnetic discharge'],
  ['doorwraith','phase','portal,needle,portal','none', 'Doorwraith. Watch where the shots come out.', 'vacuum tearing open, ghostly gate whisper, reversed pressure snap'],
  ['tidemason','weave','braid,sonic,broadside','seam', 'Tidemason incoming. Ride the gaps.', 'liquid metal surges, submarine groan, tidal magnetic whip'],
  ['parallax_hunter','phase','crossfire,needle,lance','none', 'Parallax Hunter. Three shadows. One killer.', 'phase-shifting crystal growl, quick stereo ghost echoes, electric sting'],
  ['clockray','orbit','orbit,needle,split','none', 'Clockray. Those shots will not stay frozen.', 'clockwork wing flutter, crystalline escapement ticks, sudden temporal crack'],
  ['horizon_biter','pounce','charge,broadside,bomb','jaws', 'Horizon Biter. That mouth is not decorative.', 'massive bone jaw clack, hungry subharmonic rasp, vacuum bite'],
  ['rift_surgeon','strafe','lance,crossfire,needle','none', 'Rift Surgeon. Keep moving. Keep your distance.', 'surgical diamond scrape, cutting spatial hiss, taut wire shriek'],
  ['bloom_queen','weave','petals,bomb,homing','petals', 'Bloom Queen. Beautiful does not mean friendly.', 'velvet alien trill, seedpod pops, thorny organic energy spits'],
  ['brood_ark','bomber','drone,bomb,broadside','hatches', 'Brood Ark incoming. Take out the hatcheries.', 'armored hive groan, scuttling brood, heavy organic launcher cough'],
  ['carrion_weaver','orbit','homing,split,drone','none', 'Carrion Weaver. It wants what is left of you.', 'dry scavenger rasp, bone loom ratchet, stringy electrical spit'],
  ['spore_monk','weave','mines,petals,split','none', 'Spore Monk. Do not linger in its wake.', 'breathy fungal chant without words, compressed spore cough, hollow reed rasp'],
  ['husk_parade','convoy','crossfire,drone,needle','segments', 'Husk Parade. Break the procession.', 'hollow shell procession, rattling husks, syncopated spectral snaps'],
  ['magnet_urchin','orbit','orbit,ricochet,sonic','spines', 'Magnet Urchin. Give those spines some room.', 'ferromagnetic spine rattles, bending steel twangs, bass electromagnetic punch'],
  ['chrysalis_hunter','hunt','homing,charge,flame','shell', 'Chrysalis Hunter. Crack the shell. Stay sharp.', 'taut cocoon splitting, insect wing roar, wet crystalline fracture'],
  ['rail_cathedral','strafe','rail,broadside,needle','guns', 'Rail Cathedral. Heavy guns. Small windows.', 'massive rail capacitor, resonant steel bell fragments, supersonic thunderclap'],
  ['siege_orchid','orbit','bomb,petals,barrage','petals', 'Siege Orchid. Those petals pack artillery.', 'rotating artillery petals, ceramic chamber locks, blooming mortar punches'],
  ['bulwark_hauler','bomber','broadside,bomb,ricochet','armor', 'Bulwark Hauler. Strip the armor. Find the heart.', 'heavy armored diesel-like alien drive, steel panel impacts, dense cannon reports'],
  ['bellfoundry','swoop','sonic,bomb,barrage','none', 'Bellfoundry inbound. Hear that? Duck.', 'cracked bronze bell, hot industrial exhale, percussive foundry shock'],
  ['prism_bastion','weave','prism,lance,split','mirrors', 'Prism Bastion. One beam becomes three.', 'singing optical crystal, refracted electric cracks, polished glass shatter'],
  ['cable_kraken','hunt','homing,crossfire,sonic','anchors', 'Cable Kraken. Cut the limbs before they close.', 'braided cable tension, deep mechanical beast rasp, whipping arc snaps'],
  ['switchyard','strafe','drone,ricochet,barrage','junctions', 'Switchyard. Incoming fire can change direction.', 'magnetic switch clacks, descending induction growl, electric rail whip'],
  ['false_sun','swoop','flame,petals,lance','none', 'False Sun. That light is hunting you.', 'stellar furnace inhale, brilliant plasma roar, eerie solar whistle'],
  ['mirror_court','orbit','crossfire,prism,needle','mirrors', 'Mirror Court. Shatter the accomplices.', 'whispering mirror chorus, sharp silver reflections, glassy pulse shots'],
  ['signal_thief','phase','needle,homing,barrage','none', 'Signal Thief detected. Trust your eyes, pilot.', 'encrypted radio rasp without words, carrier collapse, dry microwave crack'],
  ['lantern_mimic','pounce','homing,charge,split','none', 'Lantern Mimic. That is not a pickup.', 'innocent crystalline chirp turning into a guttural bite, predatory shimmer'],
  ['afterimage_duelist','phase','lance,crossfire,charge','none', 'Afterimage Duelist. Shoot the one that shoots back.', 'ghost blade hiss, quick dimensional double crack, close predatory whisper'],
  ['surveyor','strafe','rail,bomb,needle','none', 'Surveyor inbound. Do not give it a clean reading.', 'alien ranging chirr, articulate instrument clicks, dense focused beam snap'],
  ['cipher_engine','weave','braid,split,barrage','none', 'Cipher Engine. New pattern. Same trigger finger.', 'coded mechanical chatter, granular electric syllables without words, hard flux thump'],
  ['rainmaker','strafe','rain,bomb,needle','none', 'Rainmaker. Forecast says incoming fire.', 'storm turbine hiss, metallic raindrop flurries, wet electrical thunder'],
  ['comet_shepherd','bomber','comet,homing,broadside','fins', 'Comet Shepherd. It brought company.', 'grinding celestial stone, comet air rush, deep meteor fracture'],
  ['thunder_loom','weave','braid,lance,sonic','none', 'Thunder Loom. Find the break in the storm.', 'woven lightning crackle, thunder cloth tearing, rapid arc lashes'],
  ['avalanche_engine','bomber','barrage,comet,bomb','armor', 'Avalanche Engine. Keep your escape lane open.', 'glacial engine grind, crushing ice plate impacts, dense subzero artillery'],
  ['ricochet_duchess','orbit','ricochet,crossfire,prism','none', 'Ricochet Duchess. Watch the return shots.', 'aristocratic crystal chime without music, polished deflection pings, hot ricochet snap'],
  ['lantern_shoal','convoy','homing,petals,drone','segments', 'Lantern Shoal. The whole school bites.', 'many tiny alien lantern chirrs, schooling flutter, luminous dart snaps'],
  ['nova_anvil','hunt','charge,barrage,sonic','none', 'Nova Anvil. Stay out from under it.', 'dense tungsten hammer, star-forge pressure, monumental metallic recoil'],
  ['gilded_pilgrim','weave','crossfire,homing,petals','seals', 'Gilded Pilgrim. Make it pay for the visit.', 'antique gold resonators, spectral pilgrim breath, bright hard ceremonial weapon strike'],
  ['vault_crawler','convoy','bomb,broadside,mines','cargo', 'Vault Crawler. Crack it open, pilot.', 'sealed vault ratchets, skittering heavy machinery, armored treasure chest fractures'],
  ['oathkeeper','hunt','lance,needle,sonic','none', 'Oathkeeper. It came looking for a duel.', 'restrained ancient armored voice without words, resonant blade draw, clean ion report'],
  ['courier_zero','dive','needle,mines,split','payload', 'Courier Zero. Fast delivery. Bad intentions.', 'high velocity courier turbine, tiny payload latch, sharp courier sonic pops'],
  ['debt_collector','pounce','homing,charge,broadside','none', 'Debt Collector. Tell it we are not paying.', 'predatory debt-machine rasp, heavy coinless gear clicks, brutal vacuum punch'],
  ['mercy_trap','phase','mines,homing,flame','none', 'Mercy Trap. Nothing free out here.', 'soft lure whisper turning to a metallic snarl, trap jaws, sinister ion spit'],
  ['fortune_leech','orbit','homing,braid,needle','leech', 'Fortune Leech. Shake it off before it settles.', 'sucking spectral parasite, liquid amber gurgle, needle-sharp energy siphon'],
  ['constellation_beast','weave','crossfire,orbit,comet','nodes', 'Constellation Beast. The stars just grew teeth.', 'cosmic animal bellow, sparkling bone resonance, deep stellar hunting cry'],
  ['cathedral_of_teeth','pounce','charge,barrage,homing','teeth', 'Cathedral of Teeth. Keep every gun on that mouth.', 'cathedral stone throat, many bone teeth rattling, compact monstrous jaw thunder'],
  ['dying_star','swoop','flame,comet,petals','coolers', 'Dying Star. It plans to take you with it.', 'collapsing stellar core, strained solar howl, white hot controlled implosion'],
  ['worldmolt','hunt','bomb,charge,split','shell', 'Worldmolt incoming. Peel it apart.', 'planetary shell cracking, vast armored insect strain, living geological rupture'],
  ['choir_unbound','convoy','crossfire,sonic,orbit','singers', 'Choir Unbound. Silence them, one by one.', 'unsettling wordless alien female chorus, glass throat stabs, tightly cut vocal impacts'],
  ['eventide_engine','dive','rail,mines,barrage','engines', 'Eventide Engine. Nightfall has guns.', 'dark gravitational turbine, midnight metal howl, dense antimatter cannon crack'],
  ['witness','phase','echo,prism,homing','lenses', 'The Witness. It remembers how you fight.', 'watchful alien whisper without words, deep optical resonance, unnerving spectral weapon echoes'],
];

export const MYSTERY_COMBAT = Object.freeze(Object.fromEntries(rows.map(([id, motion, weapons, breakup, announcement, timbre], index) => [id, Object.freeze({
  id, motion, weapons: Object.freeze(weapons.split(',')), breakup, announcement, timbre, index,
  cadence: ['strafe','dive','phase'].includes(motion) ? 1.12 + index % 3 * .09 : 1.32 + index % 4 * .08,
  speed: 4.1 + index % 5 * .22,
  escapeSeconds: 27 + index % 4 * 2,
})])));
