export const REINFORCEMENT_VOICE_COUNT = 100;
export const REINFORCEMENT_DEFAULT_VOICE_ID = 'SIbt9DJkaY96v2K2fQyQ';
export const REINFORCEMENT_DEFAULT_VOICE_NAME = 'Female misfit';
export const REINFORCEMENT_MODEL_ID = 'eleven_v3';

const REINFORCEMENT_VOICE_TEXTS = [
  'Incoming enemy reinforcements. Hold the lane.',
  'Extra hostiles inbound. Keep moving.',
  'Reinforcement wave dropping in. Make it expensive.',
  'More enemy signatures on scope. Read fast.',
  'Backup just entered the sector. Rude timing.',
  'New contacts burning hot. Stay sharp.',
  'The swarm brought friends. Very optimistic.',
  'Enemy backup is punching through. Brace.',
  'Another wave has your name on it. Decline politely.',
  'Reinforcements inbound. Turn panic into score.',
  'Hostile reserves detected. Do not give them space.',
  'Sector crowding fast. Keep your exit open.',
  'Command alert. More enemies are gate-crashing.',
  'Incoming pressure spike. Hands steady.',
  'Enemy reinforcements arriving. No sightseeing.',
  'Backup wave confirmed. Let them regret it.',
  'More hostiles coming in hot. Keep the rhythm.',
  'Reinforcement signal locked. This will get loud.',
  'The lane just got company. Make room with lasers.',
  'Fresh enemies inbound. The score counter is listening.',
  'Enemy backup on final approach. Stay dangerous.',
  'Incoming reserves. This is not a drill.',
  'More targets entering play. Smile later.',
  'Reinforcements are here. They picked the wrong screen.',
  'Hostiles stacking the lane. Cut a path.',
  'Backup wave inbound. Give them the short version.',
  'New enemy wave detected. Keep your nerve.',
  'Sector alarm rising. Reinforcements incoming.',
  'More bad decisions on radar. Shoot through them.',
  'Enemy reserves dropping now. No hesitation.',
  'Incoming wave overlap. This is where legends pay rent.',
  'Backup is live. The board just got mean.',
  'Reinforcements approaching. Hold fire? Absolutely not.',
  'More hostiles inbound. Cabinet heartbeat climbing.',
  'The sector just coughed up enemies. Gross, but useful.',
  'Enemy backup detected. The screen is about to get personal.',
  'Reinforcement gate open. Stay between the gaps.',
  'Hostile wave joining the party. They were not invited.',
  'Incoming enemy surge. Keep the ship dancing.',
  'Backup wave on scope. Make their entrance brief.',
  'More swarm pressure inbound. Do not freeze.',
  'Enemy reinforcements locked in. Breathe once, move twice.',
  'Hostile reserves arriving. The safe lane expires now.',
  'Reinforcement drop imminent. Keep your hands clean.',
  'Enemy backup has arrived. Cute formation, bad plan.',
  'New contacts closing fast. No room for panic.',
  'Incoming sector trouble. Please return it damaged.',
  'Reinforcements inbound. The void just smiled wrong.',
  'More enemies on the grid. Turn fear into routing.',
  'Backup wave detected. Your lasers have appointments.',
  'Enemy reserves are stacking. Keep the center honest.',
  'Reinforcements incoming. This lane is now contested.',
  'Hostile backup inbound. Do not let them settle.',
  'Another wave is crashing in. Surf it with fire.',
  'Incoming combat spike. Stay loose.',
  'Enemy reinforcements confirmed. Make the math ugly.',
  'Backup is burning through the gate. That is dramatic.',
  'More contacts. More points. Same pilot.',
  'Reinforcement wave active. This is the spicy part.',
  'Hostiles inbound. The sector wants an argument.',
  'Enemy backup on approach. Win it before they unpack.',
  'Reinforcements detected. The screen voted against peace.',
  'Incoming reserves. Time to become unreasonable.',
  'More enemy signals on radar. Keep the line.',
  'Backup wave arriving. Do not look impressed.',
  'Hostile surge incoming. The silence was lying.',
  'Reinforcements inbound. Make the opening scene hurt.',
  'Enemy reserves at the edge. No soft corners.',
  'New hostile wave. This sector has commitment issues.',
  'Incoming reinforcements. The board is testing you.',
  'Backup confirmed. Teach them about regret.',
  'More enemies inbound. The cabinet says bonus chaos.',
  'Reinforcement alarm. This lane belongs to whoever survives.',
  'Hostile wave breach. Eyes up.',
  'Enemies incoming. They brought confidence and poor timing.',
  'Backup dropping in. Keep your drift clean.',
  'Reinforcements crossing the boundary. Do not blink.',
  'New enemy pressure. Your score smells opportunity.',
  'Hostile reserves inbound. This is the scary bit.',
  'More contacts incoming. Make fear useful.',
  'Reinforcement vector open. Cut through clean.',
  'Enemy backup is sharp. Keep your shield honest.',
  'Incoming wave. The sector is out of patience.',
  'Hostile reserves joining. Crowd control, pilot.',
  'Reinforcements inbound. Let the screen learn manners.',
  'Enemy wave arriving. Stay small, hit hard.',
  'Backup approaching. The quiet part is over.',
  'More hostiles. More noise. More you.',
  'Reinforcement spike detected. Keep the run alive.',
  'Enemy backup entering formation. Break the formation.',
  'Incoming reserves. Time to earn the legend.',
  'Hostile reinforcements. The lane is getting haunted.',
  'Backup wave confirmed. Paperwork will be intense.',
  'More enemies inbound. The stars are holding their breath.',
  'Reinforcements dropping. This is the dramatic part.',
  'Enemy reserves closing. Keep every dodge honest.',
  'Hostile wave inbound. Welcome them with bad news.',
  'Incoming backup. The sector just doubled down.',
  'Reinforcements confirmed. No mercy for clutter.',
  'Enemy surge on scope. Bring the thunder.'
];

export const reinforcementVoiceLines = REINFORCEMENT_VOICE_TEXTS.map((text, index) => ({
  id: `mission_control_reinforcements_incoming_${String(index + 1).padStart(3, '0')}`,
  text
}));
