export const ADDITIONAL_RUN_THEMES = Object.freeze([
  {
    id: 'receipt_nebula',
    label: 'Receipt Nebula',
    role: 'Delayed proof pressure',
    description: 'Splitter debts, late fragments, and lane bills arriving exactly when inconvenient.',
    primaryFormations: ['GRID', 'DOUBLE_ARC', 'SCREEN_DOOR'],
    secondaryFormations: ['SPIRAL', 'CROSS_STREAM'],
    waveTactics: ['receipt_spiral', 'traffic_court', 'plasma_bookclub'],
    threatActions: ['seed_of_regret', 'hazard_receipt', 'boomerang_invoice'],
    enemyFamilies: ['space_denial', 'simple_shooter', 'disruptor'],
    eliteRoles: ['Mine layer', 'Jammer disruptor'],
    bossArchetypes: ['carrier', 'clock', 'monolith'],
    codexTip: 'If the run starts keeping receipts, stop buying tiny mistakes.'
  },
  {
    id: 'paperclip_empire',
    label: 'Paperclip Empire',
    role: 'False helper chaos',
    description: 'Helpful-looking escorts, orbiting annoyances, and suspiciously organized office supplies.',
    primaryFormations: ['STAGGERED_WING', 'ORBIT_RING', 'BOX'],
    secondaryFormations: ['GRID', 'SIDEWINDER'],
    waveTactics: ['paperclip_parade', 'orbit_receiving_line', 'starline_bureaucracy'],
    threatActions: ['paperclip_orbit', 'forklift_crossfire', 'turnstile_cutter'],
    enemyFamilies: ['escort', 'formation_anchor', 'evasive'],
    eliteRoles: ['Drone carrier', 'Command relay'],
    bossArchetypes: ['conductor', 'choir', 'mirror'],
    codexTip: 'Ignore the cute shape. The cute shape is doing logistics.'
  },
  {
    id: 'neon_jury_duty',
    label: 'Neon Jury Duty',
    role: 'Flank verdicts',
    description: 'Pincer votes, angled testimony, and rails that object to your current location.',
    primaryFormations: ['PINCER', 'CROSS_STREAM', 'DIAGONAL_RAID'],
    secondaryFormations: ['SCREEN_DOOR', 'DOUBLE_ARC'],
    waveTactics: ['neon_jury', 'violet_switchboard', 'lunar_turnpike'],
    threatActions: ['argument_from_both_sides', 'ion_pin_lance', 'closing_argument'],
    enemyFamilies: ['sniper', 'fast_scout', 'disruptor'],
    eliteRoles: ['Sniper rail ship', 'Disruptor'],
    bossArchetypes: ['needle', 'jester', 'conductor'],
    codexTip: 'The jury sits on the sides. Clear a flank before it reaches a verdict.'
  },
  {
    id: 'lunar_turnpike',
    label: 'Lunar Turnpike',
    role: 'Curved toll traffic',
    description: 'Sidewinder arcs, moonlit crescents, and toll gates with terrible refund policy.',
    primaryFormations: ['SIDEWINDER', 'SPIRAL', 'CROSS_STREAM'],
    secondaryFormations: ['PINCER', 'ORBIT_RING'],
    waveTactics: ['lunar_turnpike', 'cryptic_horseshoe', 'sidewinder_choir'],
    threatActions: ['crescent_errand', 'lunar_backhand', 'neon_tax_lane'],
    enemyFamilies: ['evasive', 'fast_scout', 'spread_shooter'],
    eliteRoles: ['Trickster', 'Phase skimmer'],
    bossArchetypes: ['mirror', 'jester', 'vortex'],
    codexTip: 'Do not race the curve. Let the toll traffic pass and cut behind it.'
  },
  {
    id: 'static_mandala',
    label: 'Static Mandala',
    role: 'Symmetric trap ritual',
    description: 'Pretty rings, pulse symmetry, and spiritual geometry with hostile intent.',
    primaryFormations: ['ORBIT_RING', 'SPIRAL', 'GRID'],
    secondaryFormations: ['DOUBLE_ARC', 'BOX'],
    waveTactics: ['static_mandala', 'receipt_spiral', 'solar_abacus'],
    threatActions: ['pocket_supernova', 'halo_tax', 'tiny_moons'],
    enemyFamilies: ['formation_anchor', 'escort', 'space_denial'],
    eliteRoles: ['Orbit anchor', 'Shield projector'],
    bossArchetypes: ['vortex', 'clock', 'choir'],
    codexTip: 'Symmetry wants you centered. Betray it early.'
  },
  {
    id: 'cinder_trellis',
    label: 'Cinder Trellis',
    role: 'Growing lane hazards',
    description: 'Burning grids, mines, slow denial, and pressure that grows downward like a bad garden.',
    primaryFormations: ['SCREEN_DOOR', 'GRID', 'BOX'],
    secondaryFormations: ['ORBIT_RING', 'CROSS_STREAM'],
    waveTactics: ['cinder_trellis', 'traffic_court', 'gravity_minute'],
    threatActions: ['parking_violation', 'sleepy_satchel', 'hazard_receipt'],
    enemyFamilies: ['space_denial', 'slow_tank', 'formation_anchor'],
    eliteRoles: ['Mine layer', 'Turret barge'],
    bossArchetypes: ['monolith', 'forge', 'carrier'],
    codexTip: 'Hazards are seedlings. Pull them before the whole screen becomes a shrubbery.'
  },
  {
    id: 'blackbox_minuet',
    label: 'Blackbox Minuet',
    role: 'Elegant ambush timing',
    description: 'Polite late-run ambushes, graceful misdirection, and shots filed under regrettable elegance.',
    primaryFormations: ['SPIRAL', 'SIDEWINDER', 'DIAGONAL_RAID'],
    secondaryFormations: ['PINCER', 'DOUBLE_ARC'],
    waveTactics: ['blackbox_minuet', 'auction_house', 'glitch_carousel'],
    threatActions: ['false_curtain', 'redlight_greenlight', 'prism_verdict'],
    enemyFamilies: ['disruptor', 'evasive', 'charger'],
    eliteRoles: ['Phase skimmer', 'Jammer disruptor'],
    bossArchetypes: ['jester', 'mirror', 'clock'],
    codexTip: 'If it looks elegant, assume it rehearsed the ugly part.'
  },
  {
    id: 'solar_abacus',
    label: 'Solar Abacus',
    role: 'Counting-bead volleys',
    description: 'Needle arithmetic, staggered beads, and a star-powered machine that hates estimation.',
    primaryFormations: ['STAGGERED_WING', 'GRID', 'DOUBLE_ARC'],
    secondaryFormations: ['PINCER', 'SCREEN_DOOR'],
    waveTactics: ['solar_abacus', 'comet_queue', 'needle_accordion'],
    threatActions: ['hesitation_bolt', 'blueprint_lance', 'missing_slice_fan'],
    enemyFamilies: ['sniper', 'simple_shooter', 'formation_anchor'],
    eliteRoles: ['Sniper rail ship', 'Chrono splitter'],
    bossArchetypes: ['needle', 'clock', 'conductor'],
    codexTip: 'Count the rhythm once. Spend the rest of the wave shooting.'
  },
  {
    id: 'hazard_square_dance',
    label: 'Hazard Square Dance',
    role: 'Four-corner lane trading',
    description: 'Corners trade partners, crossfire changes hands, and the caller is absolutely armed.',
    primaryFormations: ['BOX', 'PINCER', 'CROSS_STREAM'],
    secondaryFormations: ['DOUBLE_ARC', 'SCREEN_DOOR'],
    waveTactics: ['hazard_square_dance', 'forklift_lattice', 'neon_jury'],
    threatActions: ['forklift_crossfire', 'argument_from_both_sides', 'auditor_fan'],
    enemyFamilies: ['spread_shooter', 'sniper', 'escort'],
    eliteRoles: ['Command relay', 'Disruptor'],
    bossArchetypes: ['choir', 'conductor', 'needle'],
    codexTip: 'The corners are dancing. Shoot the partner who keeps stepping into your lane.'
  },
  {
    id: 'violet_switchboard',
    label: 'Violet Switchboard',
    role: 'Signal routing',
    description: 'Angled calls, rerouted shots, and switchboard operators with zero customer service.',
    primaryFormations: ['CROSS_STREAM', 'DIAGONAL_RAID', 'PINCER'],
    secondaryFormations: ['SPIRAL', 'SIDEWINDER'],
    waveTactics: ['violet_switchboard', 'mirror_zipper', 'taxiway_squeeze'],
    threatActions: ['parallax_trial', 'neon_tax_lane', 'afterburner_receipt'],
    enemyFamilies: ['disruptor', 'sniper', 'evasive'],
    eliteRoles: ['Jammer disruptor', 'Phase skimmer'],
    bossArchetypes: ['mirror', 'needle', 'jester'],
    codexTip: 'When the call routes diagonally, dodge vertically. The switchboard hates that.'
  },
  {
    id: 'auction_house',
    label: 'Auction House',
    role: 'Escalating bid pressure',
    description: 'Feints, dives, fake bids, and one final hammer drop with projectile teeth.',
    primaryFormations: ['DIAGONAL_RAID', 'PINCER', 'STAGGERED_WING'],
    secondaryFormations: ['SIDEWINDER', 'CROSS_STREAM'],
    waveTactics: ['auction_house', 'glitch_carousel', 'taxiway_squeeze'],
    threatActions: ['redlight_greenlight', 'false_curtain', 'afterburner_receipt'],
    enemyFamilies: ['charger', 'fast_scout', 'disruptor'],
    eliteRoles: ['Elite hunter', 'Tractor puller'],
    bossArchetypes: ['jester', 'forge', 'needle'],
    codexTip: 'Do not bid movement on the fake. Wait for the hammer.'
  },
  {
    id: 'overrun_turntable',
    label: 'Overrun Turntable',
    role: 'Late-run remix',
    description: 'The director remixes earlier lessons into faster, rarer, louder mistakes.',
    primaryFormations: ['ORBIT_RING', 'CROSS_STREAM', 'SPIRAL'],
    secondaryFormations: ['SCREEN_DOOR', 'PINCER'],
    waveTactics: ['overrun_turntable', 'blackbox_minuet', 'starline_bureaucracy'],
    threatActions: ['royal_satellites', 'crown_bloom', 'prism_verdict'],
    enemyFamilies: ['elite_tactical', 'disruptor', 'evasive'],
    eliteRoles: ['Elite hunter', 'Command relay'],
    bossArchetypes: ['clock', 'mirror', 'vortex'],
    codexTip: 'After the target run, the machine stops teaching and starts remixing.'
  }
]);
