export const WAVE_TACTIC_VARIANTS = Object.freeze([
  {
    id: 'receipt_spiral',
    minLevel: 3,
    label: 'RECEIPT SPIRAL',
    role: 'Rotating lane invoice',
    move: 'orbit',
    shot: 'fan',
    volley: 'pulse',
    fireScalar: 1.08,
    fireDelayMult: 1.08,
    diveBias: 0.68,
    entrySpeed: 1.02,
    tip: 'Let the first receipt rotate past. The second one is the lane you actually owe.'
  },
  {
    id: 'velvet_sawtooth',
    minLevel: 4,
    label: 'VELVET SAWTOOTH',
    role: 'Soft-looking diagonal bite',
    move: 'split_sweep',
    shot: 'sweep',
    volley: 'staggered',
    fireScalar: 1.06,
    fireDelayMult: 1.06,
    diveBias: 0.96,
    entrySpeed: 0.9,
    tip: 'The diagonal teeth are gentle only in marketing. Stay under the dull edge.'
  },
  {
    id: 'traffic_court',
    minLevel: 5,
    label: 'TRAFFIC COURT',
    role: 'Lane citation pressure',
    move: 'weave_wall',
    shot: 'net',
    volley: 'pulse',
    fireScalar: 1.1,
    fireDelayMult: 1.1,
    diveBias: 0.78,
    entrySpeed: 0.94,
    tip: 'Do not appeal the whole wave. Pick one legal lane and keep moving.'
  },
  {
    id: 'lunar_turnpike',
    minLevel: 6,
    label: 'LUNAR TURNPIKE',
    role: 'Curving toll lanes',
    move: 'sweep',
    shot: 'crossfire',
    volley: 'crossfire',
    fireScalar: 1.12,
    fireDelayMult: 1.04,
    diveBias: 1.0,
    entrySpeed: 0.95,
    tip: 'The toll booths are the side ships. Clear them before the center lane gets expensive.'
  },
  {
    id: 'paperclip_parade',
    minLevel: 6,
    label: 'PAPERCLIP PARADE',
    role: 'Helpful-looking formation nonsense',
    move: 'chain',
    shot: 'burst_pair',
    volley: 'staggered',
    fireScalar: 0.96,
    fireDelayMult: 1.18,
    diveBias: 1.2,
    entrySpeed: 0.88,
    tip: 'The parade wants your eyes, not your ship. Watch the lead clip.'
  },
  {
    id: 'static_mandala',
    minLevel: 7,
    label: 'STATIC MANDALA',
    role: 'Symmetric pressure ritual',
    move: 'pulse',
    shot: 'fan',
    volley: 'pulse',
    fireScalar: 1.12,
    fireDelayMult: 1.02,
    diveBias: 0.58,
    entrySpeed: 1.0,
    tip: 'Symmetry is a trap with manners. Break to one side before the center gets holy.'
  },
  {
    id: 'forklift_lattice',
    minLevel: 8,
    label: 'FORKLIFT LATTICE',
    role: 'Cross-stacked lane pressure',
    move: 'pincer',
    shot: 'crossfire',
    volley: 'crossfire',
    fireScalar: 1.18,
    fireDelayMult: 1.04,
    diveBias: 1.08,
    entrySpeed: 0.98,
    tip: 'The side ships stack danger into the middle. Unstack one flank first.'
  },
  {
    id: 'comet_queue',
    minLevel: 9,
    label: 'COMET QUEUE',
    role: 'Staggered entry timing',
    move: 'needle',
    shot: 'needle',
    volley: 'staggered',
    fireScalar: 0.98,
    fireDelayMult: 1.2,
    diveBias: 0.74,
    entrySpeed: 1.04,
    tip: 'The queue is orderly. Dodge in small appointments, not one dramatic speech.'
  },
  {
    id: 'gravity_minute',
    minLevel: 10,
    label: 'GRAVITY MINUTE',
    role: 'Short space-control drill',
    move: 'pulse',
    shot: 'net',
    volley: 'pulse',
    fireScalar: 1.06,
    fireDelayMult: 1.12,
    diveBias: 0.62,
    entrySpeed: 0.9,
    tip: 'Anchor waves punish wandering. Decide where you live for the next few seconds.'
  },
  {
    id: 'mirror_zipper',
    minLevel: 11,
    label: 'MIRROR ZIPPER',
    role: 'Alternating lane closure',
    move: 'weave_wall',
    shot: 'fan',
    volley: 'staggered',
    fireScalar: 1.08,
    fireDelayMult: 1.06,
    diveBias: 0.82,
    entrySpeed: 0.92,
    tip: 'The zipper closes in order. Follow the teeth before they follow you.'
  },
  {
    id: 'neon_jury',
    minLevel: 12,
    label: 'NEON JURY',
    role: 'Flank verdict timing',
    move: 'pincer',
    shot: 'needle',
    volley: 'crossfire',
    fireScalar: 1.14,
    fireDelayMult: 1.08,
    diveBias: 1.1,
    entrySpeed: 0.96,
    tip: 'The jury votes from the sides. The center only records the damage.'
  },
  {
    id: 'orbit_receiving_line',
    minLevel: 13,
    label: 'ORBIT RECEIVING LINE',
    role: 'Rotating welcome committee',
    move: 'orbit',
    shot: 'burst_pair',
    volley: 'staggered',
    fireScalar: 1.0,
    fireDelayMult: 1.16,
    diveBias: 0.74,
    entrySpeed: 1.06,
    tip: 'Do not shake every hand. Slip through after the front pair fires.'
  },
  {
    id: 'cinder_trellis',
    minLevel: 14,
    label: 'CINDER TRELLIS',
    role: 'Burning grid pressure',
    move: 'pulse',
    shot: 'net',
    volley: 'pulse',
    fireScalar: 1.16,
    fireDelayMult: 1.04,
    diveBias: 0.68,
    entrySpeed: 1.02,
    tip: 'The trellis grows downward. Cut a hole early, then harvest points.'
  },
  {
    id: 'sidewinder_choir',
    minLevel: 15,
    label: 'SIDEWINDER CHOIR',
    role: 'Curved rhythm pressure',
    move: 'split_sweep',
    shot: 'fan',
    volley: 'pulse',
    fireScalar: 1.08,
    fireDelayMult: 1.12,
    diveBias: 1.0,
    entrySpeed: 0.88,
    tip: 'The choir sings from both sides. Listen for the quiet middle beat.'
  },
  {
    id: 'taxiway_squeeze',
    minLevel: 16,
    label: 'TAXIWAY SQUEEZE',
    role: 'Narrow runway denial',
    move: 'ambush',
    shot: 'sweep',
    volley: 'crossfire',
    fireScalar: 1.1,
    fireDelayMult: 1.08,
    diveBias: 1.18,
    entrySpeed: 1.0,
    tip: 'The runway is not for you. Exit before the ambush turns into traffic.'
  },
  {
    id: 'cryptic_horseshoe',
    minLevel: 17,
    label: 'CRYPTIC HORSESHOE',
    role: 'Curved surround pressure',
    move: 'orbit',
    shot: 'fan',
    volley: 'crossfire',
    fireScalar: 1.12,
    fireDelayMult: 1.08,
    diveBias: 0.86,
    entrySpeed: 0.98,
    tip: 'The open end is not always safe. Check which flank has gone quiet.'
  },
  {
    id: 'plasma_bookclub',
    minLevel: 18,
    label: 'PLASMA BOOKCLUB',
    role: 'Pattern-reading exam',
    move: 'chain',
    shot: 'net',
    volley: 'pulse',
    fireScalar: 1.08,
    fireDelayMult: 1.14,
    diveBias: 0.76,
    entrySpeed: 0.9,
    tip: 'Read the first paragraph. The second volley is just the same insult louder.'
  },
  {
    id: 'auction_house',
    minLevel: 19,
    label: 'AUCTION HOUSE',
    role: 'Escalating bid pressure',
    move: 'feint',
    shot: 'burst_pair',
    volley: 'crossfire',
    fireScalar: 1.14,
    fireDelayMult: 1.12,
    diveBias: 1.52,
    forcedDive: true,
    entrySpeed: 0.78,
    tip: 'The first bid is a fake. Spend movement only after the hammer drops.'
  },
  {
    id: 'solar_abacus',
    minLevel: 20,
    label: 'SOLAR ABACUS',
    role: 'Counting-bead volleys',
    move: 'pulse',
    shot: 'needle',
    volley: 'staggered',
    fireScalar: 1.04,
    fireDelayMult: 1.18,
    diveBias: 0.7,
    entrySpeed: 1.04,
    tip: 'Count the beads on one side. The other side will try to make you forget math.'
  },
  {
    id: 'blackbox_minuet',
    minLevel: 21,
    label: 'BLACKBOX MINUET',
    role: 'Elegant late-run timing',
    move: 'ambush',
    shot: 'fan',
    volley: 'staggered',
    fireScalar: 1.12,
    fireDelayMult: 1.1,
    diveBias: 1.0,
    entrySpeed: 0.96,
    tip: 'The minuet is graceful because it has practiced killing you. Step on the offbeat.'
  },
  {
    id: 'starline_bureaucracy',
    minLevel: 22,
    label: 'STARLINE BUREAUCRACY',
    role: 'Stacked administrative fire',
    move: 'weave_wall',
    shot: 'net',
    volley: 'pulse',
    fireScalar: 1.18,
    fireDelayMult: 1.08,
    diveBias: 0.8,
    entrySpeed: 0.9,
    tip: 'Stamp one lane approved and ignore the rest of the forms.'
  },
  {
    id: 'violet_switchboard',
    minLevel: 23,
    label: 'VIOLET SWITCHBOARD',
    role: 'Angled signal routing',
    move: 'pincer',
    shot: 'crossfire',
    volley: 'staggered',
    fireScalar: 1.16,
    fireDelayMult: 1.05,
    diveBias: 1.08,
    entrySpeed: 0.98,
    tip: 'The switchboard routes danger diagonally. Break the call by changing rows.'
  },
  {
    id: 'hazard_square_dance',
    minLevel: 24,
    label: 'HAZARD SQUARE DANCE',
    role: 'Four-corner lane trading',
    move: 'split_sweep',
    shot: 'fan',
    volley: 'crossfire',
    fireScalar: 1.14,
    fireDelayMult: 1.1,
    diveBias: 1.12,
    entrySpeed: 0.9,
    tip: 'The corners trade partners. Do not stand where the handshake lands.'
  },
  {
    id: 'orbiting_small_claims',
    minLevel: 25,
    label: 'ORBITING SMALL CLAIMS',
    role: 'Rotating claim dispute',
    move: 'orbit',
    shot: 'net',
    volley: 'pulse',
    fireScalar: 1.18,
    fireDelayMult: 1.06,
    diveBias: 0.78,
    entrySpeed: 1.02,
    tip: 'The claim rotates with the wave. Your legal defense is distance.'
  },
  {
    id: 'needle_accordion',
    minLevel: 26,
    label: 'NEEDLE ACCORDION',
    role: 'Contracting precision lanes',
    move: 'needle',
    shot: 'needle',
    volley: 'pulse',
    fireScalar: 1.06,
    fireDelayMult: 1.16,
    diveBias: 0.86,
    entrySpeed: 1.06,
    tip: 'When the lanes contract, move less. The accordion punishes big gestures.'
  },
  {
    id: 'glitch_carousel',
    minLevel: 27,
    label: 'GLITCH CAROUSEL',
    role: 'Readable rotating chaos',
    move: 'feint',
    shot: 'fan',
    volley: 'pulse',
    fireScalar: 1.12,
    fireDelayMult: 1.12,
    diveBias: 1.35,
    forcedDive: true,
    entrySpeed: 0.82,
    tip: 'The carousel fakes exits. Pick the gap after the feint, not before.'
  },
  {
    id: 'auric_bottleneck',
    minLevel: 28,
    label: 'AURIC BOTTLENECK',
    role: 'High-value narrow gate',
    move: 'weave_wall',
    shot: 'sweep',
    volley: 'crossfire',
    fireScalar: 1.2,
    fireDelayMult: 1.08,
    diveBias: 0.92,
    entrySpeed: 0.9,
    tip: 'The gold lane is bait. Shoot the anchor and make your own opening.'
  },
  {
    id: 'crystal_subcommittee',
    minLevel: 29,
    label: 'CRYSTAL SUBCOMMITTEE',
    role: 'Delayed group decision',
    move: 'chain',
    shot: 'burst_pair',
    volley: 'staggered',
    fireScalar: 1.08,
    fireDelayMult: 1.2,
    diveBias: 0.84,
    entrySpeed: 0.92,
    tip: 'The committee fires in order. Interrupt the loudest member first.'
  },
  {
    id: 'overrun_turntable',
    minLevel: 30,
    label: 'OVERRUN TURNTABLE',
    role: 'Late-run rotating remix',
    move: 'orbit',
    shot: 'crossfire',
    volley: 'pulse',
    fireScalar: 1.22,
    fireDelayMult: 1.04,
    diveBias: 0.96,
    entrySpeed: 1.04,
    tip: 'The remix keeps the beat but changes the lane. Do not memorize; listen.'
  }
]);
